### ISSUE TITLE
Housing User Story:  Find Assistance

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#1]
As a first-time home buyer, I want to find all kinds of assistance available, through grants, low-cost loans, free counseling or public resource centers, so that I can buy my first home.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
