### ISSUE TITLE
Lats/Lngs to FIPs

### ISSUE THREAD

**Issue by afrasier** [uscensusbureau/citysdk#10]
As a developer, I want to use batches of lats/lngs instead of FIPS codes.
(Batch version of #9)

**Comment by logantpowell** [comment]
As a developer, I want to define a scope boundary which would allow a user to batch request variables & geographies within by a lat/long.

E.g., "I want all the *block-groups*(geo resolution) within *this*(lat/long) *county*(geo scope)"
