### ISSUE TITLE
Query Builder

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#100]

**Comment by lgangas** [comment]
Demo

**Comment by afrasier** [comment]
Aliases/definitions

**Comment by lgangas** [comment]
to have search/find for easier

**Comment by logantpowell** [comment]
This could really rock by building #94 into the query builder. I.e., for the variable field, allow keyword entry which would have similar functionality to the Census Reporter [Type-ahead search](http://censusreporter.org/) (see: "Explore" field)

**Comment by philipashlock** [comment]
The Census Find it Connect It demos should be relevant to this:

For looking up variables: http://ds3.cnri.net/registrar/
For queries: http://ds2.cnri.net/mash/

**Comment by logantpowell** [comment]
Hells yeah, adding the ability to show results on a choropleth would be clutch :)
