### ISSUE TITLE
custom variable transformations, ala' F.R.E.D.: https://fredqa.stlouisfed.org/2014/03/27/fred-graph-how-to-creating-custom-transformation-formulas/

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#102]

**Comment by lgangas** [comment]
developer should decide how they want to use data. We can make an example/demo for one use case

**Comment by lgangas** [comment]
Logan - can you get us a use case for this?

**Comment by afrasier** [comment]
I think this burden largely falls onto the developer (at least, for the time being). An example request for what they want would be

```
var request = {
     zip: 90210
     variables: [
           "education_masters/population*income"
     ]
}
```

And they would want the output to be just that.
