### ISSUE TITLE
Choropleth Mapping tutorial/example

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#104]

**Comment by lgangas** [comment]
look at USDA example

**Comment by jmeisel** [comment]
Here's a simple example using leaflet, chloropleth, and census data already.  We could change the state population data to using the CitySDK instead of a static file.  http://leafletjs.com/examples/choropleth-example.html

**Comment by jmeisel** [comment]
one more note:  at some point I plan to ask Leaflet and others to integrate CitySDK into their own docs, replacing the need for static files like the example above has.

**Comment by lgangas** [comment]
Check out http://bl.ocks.org/mapsense-examples/00ee03b071e938ce6cc0 from mapsense

**Comment by afrasier** [comment]
Might just add Choropleth to #96 ?

**Comment by afrasier** [comment]
Added to http://uscensusbureau.github.io/citysdk/apps/chicagoCAD/

**Comment by logantpowell** [comment]
Looking good! Can we remove the black borders?

**Comment by afrasier** [comment]
I tried it with them removed and it was a bit confusing, I've just gone and trimmed them down a lot. Looks better.

**Comment by logantpowell** [comment]
:heart:
