### ISSUE TITLE
need a common interface for documentation

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#106]
make it easier for partners to plug in easier

**Comment by lgangas** [comment]
•	modulate docs so they can be open sourced (crowd-sourced) as well 

o	features 
	each feature is listed here with a teaser linking to 
	child page with example and tutorial

o	data 
	each dataset is listed here with a teaser and link to 
	aliases / definition

o	showcase

**Comment by logantpowell** [comment]
* push docs to the .io pages (keeps it out of security/bureaucracy perview)
* modulate docs so they can be open sourced (crowd-sourced) as well
 * features
  * each feature is listed here with a teaser linking to
   * child page with example and tutorial
 * data
   * each dataset is listed here with a teaser and link to
    * aliases / definition (Great for SEO :)
 * showcase
   * anyone who creates even a prototype can share it here (same parent list > child structure as above) (great for submissions for the NDoCH)

Also, if we add google analytics to the child pages, we can measure interest in features to help prioritize for inclusion the Enterprise API.
