### ISSUE TITLE
Defined Process for including modules into the CitySDK repo

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#109]
For example, why aren't the arcgis and hud modules not periodically synced into the citysdk repo

**Comment by afrasier** [comment]
Because then they'd have to go through Census OIC I believe, @logantpowell ?

**Comment by logantpowell** [comment]
@afrasier is right, anything we include in our master will have to pass security and we'd like to limit that burden for the time-being, so let's try to figure out how to make the architecture work for us to decentralize the ownership :)

**Comment by loganpowell** [comment]
closing due to age (both mine and of this issue).
