### ISSUE TITLE
Modify CitySDK to get data for further analysis

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#111]
Feedback from Forest Gregg:

I'm mainly trying to get data for further analysis, not display things on the web. Right now the CitySDK is just an nice javascript wrapper around existing APIs. If the I could really post those requests to some server and get a response back with cUrl I would be very happy.

**Comment by zhik** [comment]
Version 2 of CitySDK uses node.js , so queries can be scripted to save the data into memory or files. 
```
var fs = require("fs");

census(
  {
    vintage: 2017,
    geoHierarchy: {
      "metropolitan statistical area/micropolitan statistical area": "*"
    },
    geoResolution: "500k" // required
  },
  (err, res) => {
    fs.writeFile("./directory/filename.json", JSON.stringify(res), () =>
      console.log("done")
    );
  }
);


```
