### ISSUE TITLE
Replicate Google Maps API examples

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#116]
Demos at https://github.com/googlemaps/

Viz at https://developers.google.com/maps/articles/combining-data

**Comment by tyronegrandison** [comment]
I would suggest using MapSense:

Sample index.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content='initial-scale=1,maximum-scale=1,user-scalable=no' />

    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="http://d3js.org/topojson.v1.min.js" charset="utf-8"></script>
    <script src="https://developer.mapsense.co/mapsense.js" charset="utf-8"></script>
    <link type="text/css"  href="https://developer.mapsense.co/mapsense.css" rel="stylesheet"/>


<style>
    html, body, #myMap{
        height: 100%;
        width: 100%;
        margin: 0; padding: 0;
    }

</style>

</head>
<body>

    <div id="myMap"></div>

<script>

var map = mapsense.map("#myMap") //tell it where to go 
    .center({lon: -120, lat: 40.808}) //set a center
    .zoom(5) //set a zoom
    //.zoomRange([5,20]); // if you want to restrict zoom levels


    //tile url
    var url = "https://{S}-api.mapsense.co/universes/mapsense.demographics/{Z}/{X}/{Y}.topojson?api-key=key-2d5eacd8b924489c8ed5e8418bd883bc"; //&where=layer=='county'&dz=-2";
    //create a coloring function
    var colorRamp = d3.scale.linear()
        .domain([0,.15])
        .range(['rgb(247,251,255)', 'rgb(8,48,107)'])

    var layer = mapsense.topoJson() //init a topojson layer
        .url(mapsense.url(url).hosts(['a', 'b', 'c', 'd'])) //tell it where to look
        .clip(true)
        .selection(
            function(d){
                d.attr("class", "mapFeatures") //use a d3 selection to class each feature 
                .style("fill", function(feature){ //color each feature by its unemployment rate
                    return colorRamp(feature.properties.unemployment)
                })
            }
        );

    map.add(layer); //add the topojson layer to your map


</script>
</body>
</html>

**Comment by zhik** [comment]
Added a d3.js example [here](https://uscensusbureau.github.io/citysdk/examples/d3-map/)

Will be working on a google map api example.

**Comment by loganpowell** [comment]
@zhik has done a great job of putting together examples [in our docs site](https://uscensusbureau.github.io/citysdk/examples/).
