### ISSUE TITLE
Request for Traffic (Speed, Volume, Collision) data in City SDK

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#118]
From user developing a Safe Score for a city:  At what point might traffic data (speed, volume, collision) data be available via the City SDK? (from Jeff:  I am following up on this issue to better understand the request)

**Comment by tyronegrandison** [comment]
I had a conversation on Friday with Carey about something similar for Boston. Inclusion should not be a problem. Integrating traffic data across cities may be.

**Comment by stevevance** [comment]
Does the Census Bureau have this kind of data?

**Comment by logantpowell** [comment]
As @tyronegrandison says, Census doesn't cover this data ( [except at a very high-level](http://www.census.gov/compendia/statab/cats/transportation/motor_vehicle_accidents_and_fatalities.html), but the SDK should make it easy to include [third-party data](http://www.quora.com/Is-there-any-public-API-for-obtaining-traffic-information) depending on the curation...

**Comment by afrasier** [comment]
The TigerWeb service has a mapserver for roads and things of that nature, but the SDK doesn't currently implement access to it.(via tigerWMS_PhysicalFeatures, Transportation, or Transportation_LargeScale)

**Comment by ruiz0001** [comment]
?We don't have traffic (speed, volume, collision) data in our Transportation map service in TIGERweb. You'll need to get those data from other sources.


Thanks,

Ricardo J Ruiz
Chief, Spatial Products Software Branch
Geography Division
U.S. Census Bureau
Office: 301-763-8975
Cell: 301-367-8689
Fax: 301-763-4710
E-mail: Ricardo.J.Ruiz@census.gov
http://www.census.gov/
http://tigerweb.geo.census.gov
Connect with us:
[Twitter]<http://twitter.com/uscensusbureau>[Facebook]<http://www.facebook.com/uscensusbureau>[YouTube]<http://www.youtube.com/USCensusBureau>[Flickr]<http://www.flickr.com/photos/uscensusbureau/>

________________________________

**Comment by kberger** [comment]
Check you states for a lot of this data.  New York provides Collision data sets (no API unfortunately) https://data.ny.gov/Transportation/Motor-Vehicle-Crashes-Case-Information-Beginning-2/e8ky-4vqe and I think there were other data sets for volume either through DMV data or Depart. of Transportation data.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
