### ISSUE TITLE
A create way to download CENSUS data in bulk

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#121]

**Comment by tyronegrandison** [comment]
MapSense CEO - "For SMB and Enterprise clients, they cannot be hitting the API every time their clients want data. They need a way to do bulk downloads of CENSUS data"

**Comment by loganpowell** [comment]
This functionality is provided via FTP and thus not within scope of the primary use case of CitySDK (as of now) closing for now. Will reopen in an opportunity arises.
