### ISSUE TITLE
Need open source license or public domain notice in LICENSE.md.

### ISSUE THREAD

**Issue by kfogel** [uscensusbureau/citysdk#122]
To make clear that this code base is open source and can be freely used for any purpose, could you put the open source license (or public domain statement) in a `LICENSE.md` file at the top level?

I wasn't sure what license you wanted, but would be happy to submit a pull request with the appropriate text if you say which one.  (If public domain, that's fine too, just say the word.)

**Comment by kilrathu** [comment]
As it was created by government it is automatically public domain. With
that being said we could try for CC-0 if we want.

**Comment by kfogel** [comment]
Oh, I think public domain is fine.  I was just suggesting to put that information in a LICENSE.md file, since that's where people will usually look for it.  Would it help if I submitted a PR?

By the way, not all of the code here is in the public domain.  For example, in `js/citysdk.census.js` there is MIT-licensed code from ESRI's Terraformer project.  (Oddly, that code is included inline in the file in minified form, but that's a separate discussion. :-) .)  So the LICENSE.md notice should mention that there is a mixture of PD and open-source-licensed code here.

**Comment by kfogel** [comment]
Hmm, the `gh-pages` branch used for https://uscensusbureau.github.io/citysdk seems to have a LICENSE.md file that would be a good template: https://github.com/uscensusbureau/citysdk/blob/gh-pages/LICENSE.md

**Comment by afrasier** [comment]
Correct, the Census code is CC-0. 
The ESRI stuff is some technical debt that has yet to be paid off :) I'll push for it to be in the next sprint (as well as updating the License for the master branch)

**Comment by kfogel** [comment]
Thanks, @afrasier!

**Comment by tmcw** [comment]
In the meantime, there should be an MIT license in the repo, right?

**Comment by logantpowell** [comment]
@tmcw are you available to chat sometime about all this? Would love to collaborate...

**Comment by mateoclarke** [comment]
Would also like to see a License so we understand the implications of how we can use this moving forward.

**Comment by johnson-tor-boozallen** [comment]
License.md file migrated from the GH-pages site to the root of the project.
