### ISSUE TITLE
Need documentation on geo request for multiple zips - i.e. city of Chicago

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#124]
There is a team in Chicago building a CitySDK demo for identifying innovation spaces.  We want to configure a request that displays all the tracts in the city, from a list of zip codes.  Currently we've only been able to send the request using one zipcode.  Is it possible to get multiple tracts back (that fall into a list of zips)?  Or more generally, what is the best way for city projects to use the CitySDK to return all the tracts within a city, where a city is described by a collection of zips or some other way.  

Here's current code snippet, using only one zip for Chicago: 

var request = {
                            "zip": 60654,
                            "level": "tract"
                        };

                        var callback = function(response) {
                            map.data.addGeoJson(response);
                        };

                        census.GEORequest(request, callback);

**Comment by afrasier** [comment]
You can use a place "container". See the modified code below.

```
var request = {
     "zip": 60654,
     "level": "tract",
     "container": "place",
     "sublevel": true
};

var callback = function(response) {
     map.data.addGeoJson(response);
};

census.GEORequest(request, callback);
```

The container tag says "get all level within container", a place is the census word for an incorporated city, and sublevel says "get all of that level"

Let me know if you still have questions, otherwise, you can close this issue. :)

**Comment by afrasier** [comment]
List of common requests has been added to the guides.
