### ISSUE TITLE
Need error checking on census returned data

### ISSUE THREAD

**Issue by mpaquette1** [uscensusbureau/citysdk#127]
In CensusModule.prototype.ESRItoGEO, if the call to get census data doesn't return any features, a javascript error is thrown on line 856:
    `for(var i = 0; i < features.length; i++) {`

**Uncaught TypeError: Cannot read property 'length' of undefined**
There is similar code at line 1609 in the tigerwebRequest callback, though I haven't verified that this line throws an error.

I reproduce the problem with the following request:
`{"level":"us","zip":"55401","container":"us","variables":["employment_male_management_occupations"]}`

**Comment by afrasier** [comment]
This is the same sort of problem as #120 
Looking into it, thanks!

**Comment by afrasier** [comment]
Resolved with 85a8c34adaa7aaf99e5447a75deabc43c54bd56d
