### ISSUE TITLE
CDN for CitySDK

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#133]

**Comment by tyronegrandison** [comment]
DC Data Smoothie (URL  https://protected-shelf-4860.herokuapp.com/ )

https://hackforchange.hackpad.com/DC-Data-Smoothie-uf5pautvpgU

**Comment by logantpowell** [comment]
Not sure what this request is about.. Content Delivery?

**Comment by lgangas** [comment]
look into downloading the SDK via CDN (code distrbution network) instead of the currently way via rawgit

**Comment by loganpowell** [comment]
No longer needed. We're now an NPM library ;)

Miss you guys
