### ISSUE TITLE
Example Apps source code should run when downloaded without code changes

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#134]
It would be nice if the example apps (http://uscensusbureau.github.io/citysdk/apps/chicagoCAD/) could be downloaded and executed locally without code changes.

i.e. I want to:
1.  Copy source into my editor Sublime as a starting point for a new project
2.  Run on my local machine in browser
3.  Then begin modifying the app to customize for a new app

When I try to do this I get Failed to Load errors like: 
file:///Users/jeffmeisel/Desktop/Chicago%20Launch/blackgenesis/js/chicagocad.js Failed to load resource: net::ERR_FILE_NOT_FOUND

Perhaps all dependencies could be referenced via Rawgit link.

**Comment by afrasier** [comment]
Were you running it  on a web stack like WAMP, or MAMP? If you don't, it will error because browser's wont do CORS from local files.
