### ISSUE TITLE
API to convert ESRI to GeoJSON

### ISSUE THREAD

**Issue by afrasier** [uscensusbureau/citysdk#14]
As a developer, I want to retrieve geographical data in GeoJSON.

**Comment by philipashlock** [comment]
Here's an example of a [GeoJSON shim for TigerWeb](https://github.com/civicagency/democracymap-restserver/blob/76725fcafefb18ab24bd89c16e346dcfad3d0275/application/controllers/context.php#L1046-L1088)

Right now it's set up to take a GNIS ID and proxy it from TigerWeb as GeoJSON. For example, here it is for Austin, TX: http://rivanna.democracymap.org/context/city-boundary/2409761

**Comment by ajturner** [comment]
See [terraformer](https://github.com/Esri/Terraformer) for JS library and [Koop](https://github.com/Esri/koop) for node REST conversion service.

Cloud Hosted versions of ArcGIS Server provide GeoJSON natively.

**Comment by johnson-tor-boozallen** [comment]
Terraformer code integrated directly
