### ISSUE TITLE
Allow users to specify ArcGIS polygon selection mode

### ISSUE THREAD

**Issue by afrasier** [uscensusbureau/citysdk#142]
Allow users to specify a tag in their request that will switch among the ArcGIS polygon intersect modes. (i.e. SpatialRelIntersect, SpatialRelContains, etc...)

**Comment by loganpowell** [comment]
Closing this as we no longer use ArcGIS service for serving GeoJSON as the full-resolution payloads were not only too heavy for practical application, but they were also much more limited in the ability to pull large numbers of geographies. Moved to [static merger with cartographic boundary files](https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html). These conversions are being collected [within the `V2` repo](https://github.com/uscensusbureau/citysdk/tree/master/v2/GeoJSON)
