### ISSUE TITLE
Include national min & max for census variables where appropriate

### ISSUE THREAD

**Issue by mpaquette1** [uscensusbureau/citysdk#145]
My use case involves coloring map regions by ACS variable.  If the user is zoomed in on a state, the map will color in the that state's counties, per the chosen ACS variable; if the user is zoomed on a county, the map will color in the tracts.  I want to allow the user to be able to see where these localized data fall on the national scale.  And also give the user a basis for comparing different regions  (e.g., comparing the counties in Wisconsin to the counties in Minnesota) using the same color scale.  

I propose adding `national_min` and `national_max` to each of the aliases in citysdk.census.js that represent medians, such as: 
- income
- income_per_capita
- median age
- median_house_construction_year
- median_contract_rent 
- _other housing variables_
- commute times 
- _other "normalizable" variables_

`national_min` and `national_max` would be the lower and upper bounds of the variable's value across all census blockGroups in the US.   By giving us a national range of values, it would allow consistent map coloring no matter what geographies were being compared or at what scale.

**Comment by logantpowell** [comment]
Hi Mark,
For the colored map, I believe you're looking for the choropleth functionality... we've built an example with this included here: http://uscensusbureau.github.io/citysdk/apps/chicagoCAD/ you may also see the issue #104 for additional context...

**Comment by mpaquette1** [comment]
Thanks.  Please correct me if I missed something, but I looked at the examples and did not see where I can get the nationwide min and max for a variable, e.g., income.  My issue is not about the mechanics of rendering a colored map, but of getting the range of ACS data values without having to download & inspect every blockGroup in the US, for every variable I'm going to map.

Currently, if I use APIRequest to load an ACS variable like income for Illinois counties, my code then iterates through all the county values to find the min and max incomes in the state, and then sets up the appropriate color scheme so the max value is the top of the scale (most saturated color).  Problem is, I only then have min and max for Illinois, not nationwide.  So if the user wants to compare Illinois income vs Kentucky income by county, each state will get its own color scheme, making the comparison apples-to-oranges.  If I can somehow get the national min and national max ahead of time (preferably right in the census aliases object so no extra ajax is required), I can set up the range so that the map coloring will always be consistent across geographies.

Perhaps there's a direct call to census.gov that will give me those min & max data?

**Comment by logantpowell** [comment]
Can you add this to our [feature requests](http://apiforum.ideascale.com/a/ideas/recent/campaign-filter/byids/campaigns/9258) in our developers' forum? This will help us prioritize the request :)

**Comment by mpaquette1** [comment]
I joined the developers forum yesterday, but I'm getting this when I log in:
"A moderator has not yet approved your account."
As soon as I'm in, I'll post the question.  Should I address it directly to the CitySDK, or is this a question for the census.gov ACS back end API?

**Comment by logantpowell** [comment]
Hi Mark,


Not sure why I didn't get this notification, but you should be good to go now... Let me know if not!


Logan Powell
Web and New Media
Center for New Media and Promotion
U.S. Census Bureau

Office: 301-763-7339
Cell: 412-254-4194

census.gov<http://census.gov>
Connect with us on social media<http://www.census.gov/aboutus/social_media.html>


________________________________

**Comment by loganpowell** [comment]
In CitySDK v2 we are no longer providing aliases to Census variables as the existing maintenance burden of syncing the three underlying APIs entails significant configuration effort. Also, the list of underlying endpoints is growing and - after years of helping a broad variety of users with their use cases - it can be assumed that such aliases are use case specific and thus will need to be handled on a case by case basis. We have a number of community channels for this kind of support.

[Slack](https://join.slack.com/t/uscensusbureau/shared_invite/enQtNzI2MTY0NjA4MzU1LTYxOGE1YTVmMmU2ZjM5MjE0Yzk1NTg5Yjk4NTMxMzhhM2RjMGU5ZDMxMDgxMzMyOThiMTVlZDE0Y2ZiMjQzYjM): (`#citysdk` channel)
[Gitter](https://gitter.im/uscensusbureau/citysdk)
Email: cnmp.developers.list@census.gov
