### ISSUE TITLE
Shorten description

### ISSUE THREAD

**Issue by tmcw** [uscensusbureau/citysdk#146]
<img width="919" alt="2015-07-15 at 10 05 am" src="https://cloud.githubusercontent.com/assets/32314/8700340/2bafa1de-2ad9-11e5-958d-667371e8e829.png">

The description for this project is way too long and gets truncated. That description field should be a summary, like

> User-Friendly JavaScript SDK for US Census Bureau Data

**Comment by logantpowell** [comment]
:+1:

**Comment by tmcw** [comment]
Ping/

**Comment by jmeisel** [comment]
done
