### ISSUE TITLE
Add package.json, manage dependencies, release on npm

### ISSUE THREAD

**Issue by tmcw** [uscensusbureau/citysdk#147]
Most JavaScript modules nowadays are written with node-style commonjs includes and packaged for the browser with [browserify](http://browserify.org/). This allows you to optionally bundle jQuery and other dependencies with the code while avoiding problems like version clashes between globally-installed libraries.

This would entail: adding a package.json, making js/ files export what they create, and making a dist file.

**Comment by afrasier** [comment]
This is great stuff, I've never heard of this before. Thanks!

**Comment by logantpowell** [comment]
:+1:

**Comment by jontonsoup** [comment]
:+1:

**Comment by tmcw** [comment]
Closing: the census is still [developing in a closed environment](https://github.com/uscensusbureau/citysdk/commit/85a8c34adaa7aaf99e5447a75deabc43c54bd56d). This is not an open source project: I'll happily re-roll this patch once it is.

**Comment by rbvea** [comment]
+1, would be awesome to revisit this @afrasier

**Comment by jontonsoup** [comment]
@rbvea  I think you meant to bump @tmcw :)
