### ISSUE TITLE
filter point (e.g., crime, 311 reports, etc.) data by census geography (e.g., block-group)

### ISSUE THREAD

**Issue by logantpowell** [uscensusbureau/citysdk#15]
As per someone's suggestion, I'm adding an request for using the SDKs geo call to filter a second (mashed up) point-based (series of lat / longs) data set.  For example:

I have a bunch of locations of crimes of a certain sort
I call the SDK to dump out block-groups for my county 
I want the block groups to include: population, income and age

Hereby, I want:
use case # 1: find crimes in areas with income > $x
use case # 2: show crimes per capita for each block group (e.g., in info window on a map)
use case # 3: tally up the total crimes in each block group to find correlations between crime and income and/or age

note: this is just a hypothetical... any such point-data filtering by census geo + census data mashup is implied...

**Comment by loganpowell** [comment]
@zhik have you ever heard of functional lenses?

**Comment by loganpowell** [comment]
I'm closing this as this functionality can be provided (and more importantly, maintained) by third-party libraries, e.g., [turf.js' `collect` function](https://turfjs.org/docs/#collect)
