### ISSUE TITLE
Working in the open

### ISSUE THREAD

**Issue by tmcw** [uscensusbureau/citysdk#152]
It looks like there are sporadic, gigantic [Release commits](https://github.com/uscensusbureau/citysdk/commit/85a8c34adaa7aaf99e5447a75deabc43c54bd56d) that dump code.

Are these autogenerated commits? Merges from some other system?

It would be better for the community to work in logical chunks.

**Comment by afrasier** [comment]
I agree, but due to the way the Census handles their code we were forced to commit to an internal server for review, and then they would push it from there onto github. (With some minor exceptions)

**Comment by tmcw** [comment]
By "were" does that mean that process is no longer in place, or citysdk is no longer developed?

**Comment by jmeisel** [comment]
We did an initial 12-week development (broken into smaller sprints), our
scrumboard was publically visible here which is one way we made
communicated what was getting worked on as well as priorities:
https://waffle.io/uscensusbureau/citysdk

Arman (our lead dev) was temporarily moved off the project, and we are
onboarding some new resources to help out so the updates are slow right
now.  Hopefully we get Arman back too.

By the way, back on May 19th we hosted a workshop at 18F to kick the tires
on the project and pull in the community and partners, unfortunately Mapbox
couldn't make it on short notice.  In any event, your suggestions are
really solid and we'd love your participation or Mapbox in some capacity.
We recognize we have a ways to go on this project but really want to make
it a success.

**Comment by tmcw** [comment]
Okay: so the main question is _can you work in the open?_ Is there still a requirement to commit to an internal server and then dump to GitHub?

**Comment by jmeisel** [comment]
For next few weeks:  Answer is No for the core module.

For August and long-term:  We are trying to move CitySDK into an community
ownership model where the answer is Yes, which may mean Census contributes
but is not the main owner.  Finding the right home is still "in work" but
we are in 100% alignment that would be much much better.

**Comment by tmcw** [comment]
Okay: I'm happy to contribute once that this operates as an open source project, until then I hope that you can lobby for better policies at the Census Bureau.

**Comment by jmeisel** [comment]
Thanks Tom - really appreciate it

**Comment by tmcw** [comment]
It has been a month, any news to report?

**Comment by jmeisel** [comment]
Sorry nothing yet on working in the open, it's going slower than anticipated and I don't have an ETA at this time.  Will keep you posted.

**Comment by buckleytom** [comment]
@tmcw I believe the issue here might be more accurately captured in your point that "git commits should be made logical in logical chunks." Would it make sense to change the title of this issue? "Working in the open" is vague. What is "the open"?

**Comment by buckleytom** [comment]
@tmcw unless of course there is another issue here that i am not appreciating. in that case, maybe this should be a few separate issues?

**Comment by kfogel** [comment]
Hey @jmeisel, I really appreciate your informative answers here.  A question about something you said in one of them:

> For next few weeks: Answer is No for the core module.  [answering @tmcw's question _"can you work in the open?"_]
> 
> For August and long-term: We are trying to move CitySDK into an community ownership model where the answer is Yes, which may mean Census contributes but is not the main owner. Finding the right home is still "in work" but we are in 100% alignment that would be much much better.

Does the Census Bureau feel that there is some necessary link between doing work in the open and moving to a "community ownership model"?  (I think I get more or less what "community ownership model" means in this context, though of course could ask questions about that too.)

There doesn't have to be such a link.  If the Bureau feels that working in the open necessarily implies some fundamental change in development model, this might be an opportunity for a conversation with them about decoupling those two things (which I'd be happy to be part of if you think that would be useful).  There might be good reasons to move to a broader ownership model for the project, of course.  It's just that that's independent from the question of whether the work is done out in the open in real time.

Others have already commented on the availability of solutions for mirroring an SVN-based project out to a Git repository, so I won't add to that except to say I agree with them -- the version control system shouldn't be a blocker here.  Anyway, a Subversion repository can be out in the open too, and there are plenty of places to host them, so the whole issue of SVN->Git translation shouldn't be a blocker for working in the open.

Best regards,
-Karl

**Comment by jmeisel** [comment]
Hi @kfogel, thanks for the great feedback.  We are in fact decoupling the two items (which as you point out, don't need to be linked).  I would welcome the opportunity to pick your brain in more detail as we move ahead with some of these things.

**Comment by kfogel** [comment]
Great news!  Happy to talk any time, @jmeisel.  Ping me here, or kfogel {__AT__} opentechstrategies.com.

**Comment by jmeisel** [comment]
@tmcw @kfogel Hey guys we're on track to finalize improvements to our github policy (i.e. working in the open) and if I can have a quick call with one of you today, that would be helpful as a sanity check.  Please ping me at jeffrey.meisel (at) census.gov if you can chat on the phone for 15 minutes today.   Thx and I highly value your input.

**Comment by kfogel** [comment]
Pinged via email, @jmeisel.

**Comment by tmcw** [comment]
Any progress? About half a year since this issue was opened, it would be wonderful if the Census could do open source.

**Comment by jmeisel** [comment]
Yes we have -  just posted new policy here:
https://github.com/uscensusbureau/open-source-policy

The key point is we are able to write code in the open now.  We still have
an internal testing process to accept PRs, but aim to turn those around as
quick as possible. (and are open to automated testing as much as possible)

Thanks for the feedback as we continue to improve this over time.
Hopefully this new policy is a good step towards doing open source even if
it's not perfect.

**Comment by tmcw** [comment]
Awesome! If there are no more batch-commits, do you want to do the honors and close this ticket :)?

**Comment by kfogel** [comment]
Thanks, @jmeisel.  Is the word "internal" in "internal testing process" key here, or is it just that the Census Bureau has to do testing before it accepts a PR?  (I.e., testing can happen out in the open, if it is practical to do so, but the point is just that Census has to do it and the tests have to pass.)  Because if the requirement is that Census has to test PRs before accepting them, that sounds like a perfectly reasonable policy that most good open source projects have anyway!

**Comment by jmeisel** [comment]
It's key in the sense that our as-is process is an "internal testing
process".  My hope is we move that a more open testing process in the
future and the policy would allow us to do so.

In bullet 8 of the policy, I tried to set the stage for some of these
improvements down the road:
"Where feasible to do so, we will automate and also open source any testing
procedures and encourage contributors to execute their own tests."

**Comment by kfogel** [comment]
Sure.  That sounds to me like the actual *requirement* is that the testing happen and that Census feel confident signing off on the PR.  The rest is implementation details -- okay, so right now the only way to run those tests is internally, but hopefully in the future that gets fixed.  The internality is not a requirement per se.

I guess I'm just saying that you're closer to open source norm than you're giving yourself credit for :-).  Obviously, the maintainer of a given copy of the code (in this case, the socially accepted "master" copy) has to review & vet PRs before merging them.  As the responsible party for this copy, Census is doing so.  That's certainly nothing to apologize for.

**Comment by jmeisel** [comment]
Thanks all for the feedback and support in improving our process.  

As mentioned, the policy will live here moving forward:
https://github.com/uscensusbureau/open-source-policy

**Comment by waldoj** [comment]
:+1:!
