### ISSUE TITLE
The returned maps are rather bad for Maryland

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#153]
From Margie (mroswell@gmail.com), 

"I just checked out the CitySDK video. The returned maps (forgive me...) are rather bad for Maryland. I hope whomever is behind CitySDK can update Maryland maps (state and county boundaries) to ones that we'll actually want to use, i.e. that recognize the existence of the Chesapeake Bay (and, likely, same issue for Michigan and the Great Lakes)."

**Comment by ruiz0001** [comment]
The maps lineup with the legal boundaries for all entity types.  These legal boundaries extend three miles into the oceans and are almost always somewhere within a body of water (lake or river) as you noticed in the case around the Great Lakes.


Thanks,


Ricardo J Ruiz, GEO, U.S. Census Bureau

Ricardo.J.Ruiz@census.gov

census.gov<http://www.census.gov/>   Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>


________________________________
