### ISSUE TITLE
Research long-term scaling of modular architecture and Census Module contents

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#158]
Currently all the Census APIs are put into a single Module (i.e. the Census Module).   As we look to add more Census datasets, it may make sense for a module to have a 1-1 mapping to the dataset.  

In addition, there may be other refactoring that needs to happen to the Census Module, if there is functionality that should be more broadly available to users (without adding that specific module).

**Comment by loganpowell** [comment]
@jmeisel the v2 of CitySDK now allows you to you *all* of the Census API endpoints. 🚀
