### ISSUE TITLE
Add more Census datasets

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#159]
The CitySDK currently only supports ACS.

This user story is to add in the additional datasets to the project to cover more use-cases for our users.  (I am working to secure the order of priority as we speak)

**Comment by jmeisel** [comment]
Order of importance:

General
1. http://www.census.gov/data/developers/data-sets/decennial-census-data.html

Focus on Business for upcoming hackathon
1. http://www.census.gov/data/developers/data-sets/business-dynamics.html
2. http://www.census.gov/data/developers/data-sets/economic-indicators.html
3.  http://www.census.gov/data/developers/data-sets/nonemployer-statistics-and-county-business-patterns.html
4. http://www.census.gov/data/developers/data-sets/economic-census.html
5.  http://www.census.gov/data/developers/data-sets/Annual-Survey-of-Manufactures.html

**Comment by PureLeaf** [comment]
Currently working on the Decennial dataset.

**Comment by tfmontague** [comment]
When will the Decennial dataset be accessible? I'm trying to use the existing CitySDK for the Decennial alias: population_2010, and it's just not working. Not sure why the Decennial aliases are listed if they aren't usable (http://uscensusbureau.github.io/citysdk/guides/censusModule/aliases.html).

Looks like the API defaults to "acs5". Tried the following request, without success -
`
var request = {
  // api:"sf1",
  state: "CA",
  level: "place",
  sublevel: true,
  variables: [
    "population_2010"
  ]
};
`

Also tried to cURL the data, with the URL documented on the USCensus website (http://www.census.gov/data/developers/data-sets/decennial-census-data.html), but that doesn't work either.

`curl http://api.census.gov/data/2010/sf1?key=API_KEY&get=P0010001,NAME&for=state:*`

The following message appears in the JSON response {... "c_unavailableMessage": "This dataset is currently unavailable." ...}. Again, not sure why this URL example is documented if it's not usable.

Am I using these APIs incorrectly?

**Comment by PureLeaf** [comment]
Hi Tim,


I apologize for not syncing the release of the Decennial module with the updated home page.  I've attached the module to this email.


The module in the process of getting approval for posting on the page.


Your request looks correct.  You will have to use declare a different module when using the Decennial data set:


sdk = new CitySDK();
census = sdk.modules.census;


I hope that helps.  And thanks for your patience.



David Lee

CAT Support Team, Booz Allen Hamilton

Android Developer

Chief Technology Office

U.S. Census Bureau

david.lee@census.gov<mailto:david.lee@census.gov>

lee_david@bah.com<mailto:lee_david@bah.com>

Cell (703) 597-8217


________________________________
