### ISSUE TITLE
Guide:  Build a module with Parse

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#161]
This user story is to write a tutorial that explains how someone can build an API using Parse, and then integrate that as a CitySDK module.

It also serves as an example of using a mobile-friendly backend integration, as Parse is typically used for both web and mobile applications.

**Comment by logantpowell** [comment]
Since Parse is now shutting down, I'm gonna close this issue:

http://blog.parse.com/announcements/moving-on/
