### ISSUE TITLE
Expand the Query Builder Demo

### ISSUE THREAD

**Issue by johnson-tor-boozallen** [uscensusbureau/citysdk#183]
Modify the Query Builder Demo Page (http://uscensusbureau.github.io/citysdk/guides/censusModule/queryBuilder.html) so that it is capable of accepting any census variable in addition to the built-in aliases.

Also enhance the visual layout of the form.

**Comment by logantpowell** [comment]
:+1:

**Comment by mpaquette1** [comment]
very cool, thanks!


*Mark Paquette*
Co-founder & CTO
thedatabank, gbc. (general benefit corporation
<https://en.wikipedia.org/wiki/Benefit_corporation>)
612-455-3502
mark@thedatabank.com
