### ISSUE TITLE
National Weather Service Module

### ISSUE THREAD

**Issue by johnson-tor-boozallen** [uscensusbureau/citysdk#191]
Create a module to retrieve data from NOAA's REST API

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
