### ISSUE TITLE
Integrate 2010-2014 5-year ACS data

### ISSUE THREAD

**Issue by stevevance** [uscensusbureau/citysdk#192]
The Census bureau released the 2010-2014 5-year American Community Survey data today, and this is the first time we have two, non-overlapping 5-year datasets. 

When will this be available in CitySDK/Census API?

**Comment by johnson-tor-boozallen** [comment]
An update to CitySDK to use this data is currently being reviewed.  Expect an update in days rather than weeks.

**Comment by jmeisel** [comment]
@stevevance Note the Census API has been updated with the new ACS data, available now via census.gov/developers. As @johnson-tor-boozallen mentioned, the CitySDK minor edits to allow for this new dataset should be reviewed and then published in the next few days.
