### ISSUE TITLE
Add Commuting (Journey to Work) data and example 

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#194]
In preparation of an upcoming developer event in DC supporting Dept of Transportation, the request is to add a commuting example and supporting datasets (assuming they can't already be extracted by ACS directly).  This page has more info on: http://www.census.gov/hhes/commuting/data/commutingflows.html

**Comment by johnson-tor-boozallen** [comment]
I shall get right on this.  When is the event?

[base email logo]

Tor N. Johnson
Associate
Desk: 571-346-4331
Mobile: 703-862-5790
Johnson_tor@bah.com<mailto:Johnson_tor@bah.com>

**Comment by jmeisel** [comment]
Sorry I should have clarified - it's not until early Feb so don't consider it super urgent.  Just wanted to get it in the backlog now and on your radar.  Completion by end of December would be ideal in order to get thorough testing and stakeholder feedback prior to the event.
