### ISSUE TITLE
Housing User Story: Find Properly Licensed Agents and Brokers

### ISSUE THREAD

**Issue by dermidgen** [uscensusbureau/citysdk#2]
As a home buyer moving to a new area, I want to find all the properly licensed agents and brokers, so that I can safely and objectively choose an agent to help me find my new home.

**Comment by jmeisel** [comment]
Thanks for the comment dermidgen, we haven't decided how to handle commercial-oriented services in the SDK so that's something I'll bring up with the team.  Do you know of a public data source for that information, does HUD provide that for example?  I agree the user story you suggested would be useful.  If it doesn't make sense to include directly, it might be something that another party develops and the City SDK can reference.  In any event -- awesome user story

**Comment by dermidgen** [comment]
Thank you. I wasn't able to apply the "user stories" label like you ask; permissions thing.

As I understand it, this is public data, maintained at a state licensing level. I haven't found anything yet from HUD but I am still looking. I was hoping Census Bureau would have something. I will update here if I do find anything.

Presently, the only source I have found, indexed by data.gov, is from the state of Hawaii. Unfortunately they have not provided raw data but a web site that performs a reverse lookup from the license number. Independently of data.gov, I have found most other states offer similar services.

http://catalog.data.gov/dataset/professional-and-vocational-licensing-pvl-search-90591

**Comment by jmeisel** [comment]
Thanks for the info.  I'll look into that link.   I'll also ping the HUD folks that are helping out with City SDK and see if they know anything, as well as look into other sources that may host the info.  (I don't think Census has this specifically, could be wrong though)

The issue tracker may require me as owner to add the label, but in any event your user story format was exactly what we are looking for.

**Comment by dermidgen** [comment]
Wonderful. Here's another example of where these data may be lurking. The state of California's data.ca.gov portal links through to a number of underlying sources for licensing data. (I could see a variety of useful user stories emanating around accessibility to legally licensed resources/entities/individuals.)

http://data.ca.gov/2011/12/21/professional-licenses/ -> http://www2.dca.ca.gov/pls/wllpub/wllquery$.startup -> http://www2.dre.ca.gov/PublicASP/pplinfo.asp

Perhaps your folks can identify more stakeholders from that chain. If there's anything further I can do to help, please let me know.

**Comment by connorjmcd** [comment]
I'm late to this thread but I'm not aware of any data that HUD has on state licensed agents and brokers.  What I am aware of are (a) a list of FHA-approved lenders: http://www.hud.gov/ll/code/llslcrit.cfm (b) registered brokers who are approved to bid on "HUD Homes" which are FHA-foreclosed properties that are being resold: http://www.hudhomestore.com/Listing/BrokerSearch.aspx?sLanguage=ENGLISH

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
