### ISSUE TITLE
Interactive Documentation

### ISSUE THREAD

**Issue by afrasier-bah** [uscensusbureau/citysdk#20]
Add support for interactive documentation

**Comment by afrasier-bah** [comment]
Page to demonstrate SDK variables/functionality with no cdoe

**Comment by logantpowell** [comment]
http://data.hud.gov/housing_counseling_form.html

**Comment by logantpowell** [comment]
Not sure if this would be useful... http://devdocs.io/

**Comment by afrasier-bah** [comment]
Resolved 97d7c58cbd3c958c4314599b9e431a7ab3a86935
