### ISSUE TITLE
Feature request: Time-series wildcard parameter

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#204]
As more datasets get added to CitySDK, there is a need for time-series data to be able to have a wildcard parameter to return all the latest data in a time-series set.  Currently, users must call a time-series API one call at a time which is frustrating.  The example use-case is data from SAIPE http://www.census.gov/did/www/saipe/

**Comment by johnson-tor-boozallen** [comment]
Prerequisite #205

**Comment by loganpowell** [comment]
Fixed in v2 with `predicates`
