### ISSUE TITLE
Add Time Series Census Data Sets

### ISSUE THREAD

**Issue by johnson-tor-boozallen** [uscensusbureau/citysdk#205]
Add the time series data sets to the census module (ones that do not have a year specification on http://api.census.gov/data.html)

**Comment by kuanb** [comment]
Is that link a list of available resources through the Census API? If so, is the intent to tag the datasets that don't have dates with dates? Because they are currently listed as N/A, does that mean that the solution is to manually add logic that certain endpoints are associated with certain dates?

**Comment by loganpowell** [comment]
Done in v2 (for statistics)
