### ISSUE TITLE
Add more CKAN info to Gallery

### ISSUE THREAD

**Issue by jqnatividad** [uscensusbureau/citysdk#209]
Similar to the other modules here - https://uscensusbureau.github.io/citysdk/gallery.html

**Comment by johnson-tor-boozallen** [comment]
Combining this issue #208

**Comment by johnson-tor-boozallen** [comment]
In the shorter term, we've also posted up the function reference for CKAN to: https://uscensusbureau.github.io/citysdk/guides/developer/citysdk.ckan.html

It's been added as an entry in the gallery
