### ISSUE TITLE
"Browse by" buttons are broken

### ISSUE THREAD

**Issue by rossdakin** [uscensusbureau/citysdk#212]
On the gallery page, the filter buttons aren't functional:

<img width="483" alt="screen shot 2016-01-21 at 4 29 49 pm" src="https://cloud.githubusercontent.com/assets/44956/12495167/428235b6-c05c-11e5-9cda-9360e1c8b62c.png">

This is because the page is served over HTTPS but the isotope.js library is being loaded via HTTP.

```
Mixed Content: The page at 'https://uscensusbureau.github.io/citysdk/gallery.html' was loaded over HTTPS, but requested an insecure script 'http://isotope.metafizzy.co/v1/jquery.isotope.min.js'. This request has been blocked; the content must be served over HTTPS.

gallery.html:450 Uncaught TypeError: $gallery.isotope is not a function
```

**Comment by rossdakin** [comment]
It looks like the proper source to reference for this script (according to the [docs](http://isotope.metafizzy.co/#cdn)) is https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.min.js

**Comment by johnson-tor-boozallen** [comment]
I just spotted the issue - the page DOES work when viewed in http but does not work in https.  For today, give the page a try without using SSL.  I'll get this patched shortly.

**Comment by rossdakin** [comment]
I just realized that `gh-pages` doesn't mirror `master` — I thought maybe the gallery page had been deprecated, but now I realize the branches just serve totally different purposes.

Will open a PR soon!
