### ISSUE TITLE
QUESTION: Where is the public scrumboard?

### ISSUE THREAD

**Issue by josephbooth** [uscensusbureau/citysdk#237]
I read an article on the Census Intranet site this morning. It mentioned that CitySDK has a public scrumboard. Where do I go to see this?

Thank you.

**Comment by logantpowell** [comment]
https://waffle.io/uscensusbureau/citysdk just sign up/in with your github account.

**Comment by kilrathu** [comment]
Hi Joseph,

You can find the CitySDK scrumboard here:
https://waffle.io/uscensusbureau/citysdk.

Best,

Alex

**Comment by johnson-tor-boozallen** [comment]
We have our scrum board posted to: https://waffle.io/uscensusbureau/citysdk


[base email logo]

Tor N. Johnson
Associate
Desk: 571-346-4331
Mobile: 703-862-5790
Johnson_tor@bah.com<mailto:Johnson_tor@bah.com>

**Comment by josephbooth** [comment]
Awesome! Thank you all for the information.
