### ISSUE TITLE
Census TIGER ArcGIS resource isn't loading

### ISSUE THREAD

**Issue by stevevance** [uscensusbureau/citysdk#239]
I am receiving the error that `http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/8/query` cannot be loaded. 

![screenshot 2016-03-11 23 44 47](https://cloud.githubusercontent.com/assets/1330459/13721175/6878b8f4-e7e3-11e5-8b48-cccd5b6f3ac9.png)
You can see the error in my production site, [Chicago Cityscape](http://www.chicagocityscape.com/places.php?place=chipolicebeat-district-01-beat-0111).

Did the endpoint URL or something else change? I hadn't touched my code in months, and I went to test my webpage today for a client and saw that CitySDK wasn't working as expected.

**Comment by ruiz0001** [comment]
TIGERweb no longer supports HTTP. Please use HTTPS.


Thanks,


Ricardo J Ruiz, PMP, Chief, Spatial Products Systems Branch, Decennial Information Technology Division, U.S. Census Bureau

Office 301.763.8975<tel:301.763.8975>   Cell 301.367.8689<tel:301.367.8689>   Fax 301.763.4710<tel:301.763.4710>   Ricardo.J.Ruiz@census.gov<mailto:Ricardo.J.Ruiz@census.gov>

census.gov<http://www.census.gov/>   Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>


On Mar 12, 2016, at 12:46 AM, Steven Vance <notifications@github.com<mailto:notifications@github.com>> wrote:


I am receiving the error that http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/8/query cannot be loaded.

[screenshot 2016-03-11 23 44 47]<https://cloud.githubusercontent.com/assets/1330459/13721175/6878b8f4-e7e3-11e5-8b48-cccd5b6f3ac9.png>
You can see the error in my production site, Chicago Cityscape<http://www.chicagocityscape.com/places.php?place=chipolicebeat-district-01-beat-0111>.

-

**Comment by stevevance** [comment]
Okay, I believe that fixed it. Thank you.
