### ISSUE TITLE
Defining a batch call by lat/long + geographic scope + geographic resolution (e.g., give me all the blocks within *this* county).

### ISSUE THREAD

**Issue by logantpowell** [uscensusbureau/citysdk#24]
As a developer, I want to define a scope boundary which would allow a user to batch request variables & geographies within by a lat/long.

E.g., "I want all the *block-groups*(geo resolution) within *this*(lat/long) *county*(geo scope)"

**Comment by afrasier-bah** [comment]
I'm limiting this to the first sub-level for a specified level. For instance, if a user requests sublevels for a state, it will return all counties. Basically:

u.s. -> states
state -> counties
county -> tracts
tract -> blockGroups

For the time being. We can look at removing this limitation in a future iteration.

**Comment by logantpowell** [comment]
Brilliantly lean (and agile) idea :)

**Comment by afrasier-bah** [comment]
Resolved by d93e83f38bd472ca10e9bc6d96b0960a16110398
