### ISSUE TITLE
CDN version not up to date

### ISSUE THREAD

**Issue by iloveluce** [uscensusbureau/citysdk#246]
The CitySDK Census module version served through the provided CDN is a much older version (presumably 1.1)
<img width="416" alt="screen shot 2016-04-15 at 2 51 51 am" src="https://cloud.githubusercontent.com/assets/2956449/14553603/746f7304-02b5-11e6-995a-560d7038dac4.png">
than the one currently used on the examples site (presumably 1.5) 
<img width="440" alt="screen shot 2016-04-15 at 2 52 09 am" src="https://cloud.githubusercontent.com/assets/2956449/14553623/870fb938-02b5-11e6-8792-bdeefb0bb1f0.png">

as well as the latest version on the master branch (also appears to be 1.5). 
<img width="407" alt="screen shot 2016-04-15 at 2 52 00 am" src="https://cloud.githubusercontent.com/assets/2956449/14553666/c782f07a-02b5-11e6-8af5-19b695827267.png">

Causing many issues when using the CDN version to attempt to re-create examples. Including an observed issue with attempting to retrieve ACS data for newer years.

Thanks for all your work!

**Comment by logantpowell** [comment]
Great catch, @lucianoiscool ! @johnson-tor-boozallen @jmeisel can we prioritize this?

**Comment by loganpowell** [comment]
@iloveluce with v2, citysdk is now an NPM library.
