### ISSUE TITLE
Pull Census boundaries by custom / locally-defined boundary (e..g, give me the average income from all the tracts within  'queens').  Users - LEHD, HUD

### ISSUE THREAD

**Issue by logantpowell** [uscensusbureau/citysdk#25]

**Comment by logantpowell** [comment]
I was stopped in my tracks! I need to be a collaborator in order to edit this...

e.g., "Pull all Census Tracts within this 'Neighborhood'"

**Comment by afrasier-bah** [comment]
Custom geographies are supported via ArcGIS on Tigerweb which we'll use to accomplish this.

**Comment by afrasier-bah** [comment]
Resolved 97d7c58cbd3c958c4314599b9e431a7ab3a86935
