### ISSUE TITLE
Error when adding variables

### ISSUE THREAD

**Issue by wbconnelly** [uscensusbureau/citysdk#257]
Here is the form of my request:

```
    var request = {
            "lat": 25.7823072,
            "lng": -80.30112,
            "level": "county",
            "sublevel": true,
            "variables": ["population", "income"]
        };
```

and I get the following error message:

jquery-2.1.4.min.js:4 GET file://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-80.3011…at=jsonp&callback=jQuery21405900524758206962_1461343832905&_=1461343832906 net::ERR_FILE_NOT_FOUND

Not sure why this is happening.  Also where can I find a list of variables I can pass with the request?

full code below:

<html>

<head>

<script src="http://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript"></script>

<script src="http://uscensusbureau.github.io/citysdk/static/js/citysdk/citysdk.js"></script>

<script src="http://uscensusbureau.github.io/citysdk/static/js/citysdk/citysdk.census.js"></script>

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.5/leaflet.css" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.5/leaflet.js"></script>

<script src="http://matchingnotes.com/javascripts/leaflet-google.js"></script>

</head>

<body>

<div id = "list"></div>

<div id="mapid" class = "col-md-10 col-md-offset-1" style="border: solid darkgrey; border-radius: 10px; margin-top: 30px; height: 750px"></div>

</body>

<script>

var center = [36.8774324, -76.2926687]
var mymap = L.map('mapid').setView(center, 4);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=' + 'pk.eyJ1Ijoid2Jjb25uZWxseSIsImEiOiJjaW1pN2w2MncwMDYydXlrdTNyMHR6aWdwIn0.E-vP5rCL3l6lOLyfU0FyIA', {
    id: 'mapbox.emerald'
}).addTo(mymap);

var sdk = new CitySDK(); //Create the CitySDK Instance
census = sdk.modules.census; //Create an instance of the module
census.enable("d19905ab1714245cce227557b81d4cf28be31fcd"); //Enable the module with the api key

var sdk = new CitySDK();
var census = sdk.modules.census;

var geoCities = {
        "Asheville_NC": [35.5800, -82.5558],
        "Austin_TX": [30.2500, -97.7500],
        "Boston_MA": [42.3601, -71.0589],
        "Chicago_IL": [41.8369, -87.6847],
        "Fargo_ND": [46.8772, -96.7894],
        "Montgomery_County_MD": [39.1319, -77.2264],
        "NYC_NY": [40.7127, -74.0059],
        "Portland_OR": [45.5200, -122.6819],
        "San_Francisco_CA": [37.7833, -122.4167],
        "Seattle_WA": [47.6097, -122.3331],
        "Washington_DC": [38.9047, -77.0164]
    };

var city = "Chicago_IL"

var lat = geoCities[city][0]
var lng = geoCities[city][1]

console.log(lat, lng)

    var request = {
            "lat": 25.7823072,
            "lng": -80.30112,
            "level": "county",
            "sublevel": true,
            "variables": ["population", "income"]
        };

census.GEORequest(request, function(response) {
            L.geoJson(response).addTo(mymap);
            console.log(response);
            });

</script>

</html>

**Comment by johnson-tor-boozallen** [comment]
I think I see what is causin' mischief.  The library uses the default protocol that the browser users in several places to allow for both http and https communication.  The error you are seeing shows a "file://" protocol being used.  Am I correct in guessing that you are running the file locally by loading the html directly into your browser?  If so, then your issue isn't a cross-domain issue but instead need to run the code on a server of some type (it can be a local server on your computer).  In short, the html must be accessed via http or https to function.



Alternatively, you can override the urls in the library with the newer versions of CitySDK with manually defined http or https urls.





________________________________

**Comment by wbconnelly** [comment]
That's solved it.  Thanks.  I just ran the file from a local server and it worked fine.
