### ISSUE TITLE
Error 404 While clicking on the source code link

### ISSUE THREAD

**Issue by neilmartis** [uscensusbureau/citysdk#259]
When you click on the examples link on the homepage and it takes you to example page and source code option via the tab.When clicked on the source code link it gives a 404 error code.Screenshot attached below.
![sourcecode](https://cloud.githubusercontent.com/assets/10228512/14897140/c825c2ca-0d4e-11e6-9c96-478f5e1c559e.PNG)

**Comment by johnson-tor-boozallen** [comment]
We recently reworked how the code examples are displayed and migrated them to reside within the example page.  I think you may have an older version of the example page cached in your browser.  If you do a hard-refresh, then the link to the external source code page should vanish and a new code example tab should appear farther down the page.

**Comment by neilmartis** [comment]
@johnson-tor-boozallen Thanks
