### ISSUE TITLE
Cross-Origin Request issue

### ISSUE THREAD

**Issue by damaneice** [uscensusbureau/citysdk#263]
I am attempting to use the GEORequest function that is apart of the SDK. When I make a request from inside of my app using the sdk I receive the following error. 

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/86/query. (Reason: CORS header 'Access-Control-Allow-Origin' missing)."

**Comment by logantpowell** [comment]
If you could refer to issue #200 and build upon that, please.

**Comment by tshrestha** [comment]
@damaneice we are currently working on resolving this issue. As a temporary workaround you could change the endpoint for tiger web to use `https` instead of `http`. For example:

```
CensusModule.prototype.DEFAULT_ENDPOINTS.tigerwebURL = "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/";
```
