### ISSUE TITLE
Remove Query Builder dependency or overall CitySDK dependency on Geocoder for simple State/County queries

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#264]
For data only requests, I suggest we review the Geocoder dependency for common API calls that can be made via the CitySDK, and determine if it's absolutely necessary to go through the Geocoder.  (I'm not sure if this is a limitation with the Interactive Query Builder, or the CitySDK itself).  Many times a user says "give me median income data for all the counties in Florida".

Suggested implementation is a simple geo lookup function for API calls that are intended to return Data API values only, at common levels like State and County, and bypass going through Geocoder.  i.e. a basic FIPS lookup could be applied using this mapping http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt, for a good percentage of common API requests that only require data. 

The code snippet below is an example call I'd like to be able to make, comparing female vs. male occupation data.  I just want data values only, but if Geocoder/TIGERweb is undergoing maintenance my experience with the Query Builder has been the CitySDK request will not provide a correct response.  This seems like an artificial dependency because there shouldn't be a real need for advanced geocoding in this use-case, it's a much simpler mapping exercise than a lat/lon to Census tract or something more complex.  

{
    "level": "county",
    "state": "TX",
    "variables": [
        "employment_female_computer_engineering_and_science_occupations",
        "employment_male_computer_engineering_and_science_occupations"
    ],
    "api": "acs5",
    "year": "2014"
}

**Comment by loganpowell** [comment]
Done (v2) ;)
