### ISSUE TITLE
Provide fast loading shapes for common geo requests via CDN - for demo purposes and training events

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#265]
I'd like a few demo options on the CitySDK site for training workshops and onboarding new users, that will be accessible even in the event of API maintenance.  

For State shape file requests, or county shape file requests, I'd like for CitySDK to provide "good enough" quality polygons that are memory optimized (for faster rendering in a web app) directly from a CDN (or existing open-source project that can be leveraged) without going through TIGERweb or Geocoder.   These shape files should always be accessible as a form of redundancy, for demo purposes.

**Comment by tshrestha** [comment]
@jmeisel As an alternative to a CDN we could use an AWS S3 bucket. It basically acts as an CDN is great for serving static content. Just wanted to throw out an option in case we get access to AWS.

**Comment by loganpowell** [comment]
Done. :)
