### ISSUE TITLE
Leverage (re-use) Census Reporter viz capabilities to City SDK

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#27]

**Comment by afrasier-bah** [comment]
Create an example/demo demonstrating the use of the SDK with a charting library (e.g. google charts, high charts).

**Comment by logantpowell** [comment]
http://ryanpitts.com/presentations/nicar-2014/responsive-charts/#/

**Comment by logantpowell** [comment]
Here's a link to their blog post about leveraging their mapping (leaflet) functionality: 

http://censusreporter.tumblr.com/post/112435574469/more-ways-to-use-census-boundaries-on-your-slippy
