### ISSUE TITLE
Add Air Quality (EPA) dataset, beta tester:  CityMatters

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#28]

**Comment by afrasier-bah** [comment]
Moved back to backlog due to CORS/JSONP issue.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
