### ISSUE TITLE
Census Model Query builder - cannot select dataset or year 

### ISSUE THREAD

**Issue by lstillwe** [uscensusbureau/citysdk#281]
Trying to use Census Model Query builder here: https://uscensusbureau.github.io/citysdk/guides/censusModule/queryBuilder.html
and I am unable to select a dataset or year in the drop-downs. Please advise.

**Comment by tshrestha** [comment]
@lstillwe I can't duplicate the problem. I went to the query builder page and I was able to see a list of all the datasets after clicking the **Dataset** dropdown. I was also able to select the year.

If you're still having this issue could you please provide some more details?

**Comment by tshrestha** [comment]
@lstillwe closing this issue. Please let me know if you're still having an issue with the query builder.
