### ISSUE TITLE
Does not work as a server-side npm module

### ISSUE THREAD

**Issue by liorrm** [uscensusbureau/citysdk#287]
Hi there, super excited about this package, but it doesn't  work as a server-side npm module (even when I follow the example provided on the npm website), as it has a hard dependency on browser-only objects like the window. Happy to contribute to a refactor - let me know if that's something you guys would be open to.

Cheers!

**Comment by logantpowell** [comment]
We are always very appreciative of contributions @liorrm!

**Comment by tshrestha** [comment]
@liorrm the Node version is currently under work. You can also experiment with the code in the [node-api](https://github.com/uscensusbureau/citysdk/tree/master/node-api/src) modules. These modules have been modified to work on the server side using Node.js. Although, there is a caveat - the node version in the master branch is not final and is still being improved. A more stable version will be released in v0.2.0.
