### ISSUE TITLE
Add Energy Outage dataset, beta tester:  CityMatters

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#29]

**Comment by mikelmaron** [comment]
@jmeisel does this have any overlap with Denise's work at DoE?

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
