### ISSUE TITLE
Census Demographic Data For d3.js 'Coldmap' Visualization

### ISSUE THREAD

**Issue by essejhsif** [uscensusbureau/citysdk#3]
Heat Seek NYC would like to add city-level demographic data to our 'coldmap' visualization (developed in d3.js).  The coldmap, which shows number of heating complaints per zip code, can be found here: http://heatseeknyc.com/coldmap

One interesting metric to include with the coldmap visualization would be the average income for a given household/zip code. Additional data that would be great to show next to housing temperature data - based on functions listed at https://uscensusbureau.github.io/citysdk/functions.html - would be avg_age(), housing_avail(), and job_stats()

Also, Heat Seek NYC will be adding other visualizations based on the data that our temperature sensors collect. Seeing demographic data next to this data will also be useful for analytics, exploration and ultimately 'telling a story' through the use of visualizations.

**Comment by jmeisel** [comment]
Thanks for the suggestion Jesse.  We definitely hope to provide visualization capabilities within the City SDK, specifically around D3 to help enable this type of functionality (either through code or technical guides).

**Comment by essejhsif** [comment]
Great, thanks! Even grabbing the data and being able to visualize outside of the SDK using d3.js would be great. Question: what will be the output format for function calls? JSON?
