### ISSUE TITLE
New Endpoints for Some Variables (Time Series)

### ISSUE THREAD

**Issue by logantpowell** [uscensusbureau/citysdk#303]
We got a heads-up from the powers that be:

These are Datasets that will be moved as of 10/31/16:
- http://api.census.gov/data/eits/ftd
- http://api.census.gov/data/eits/hv
- http://api.census.gov/data/eits/m3
- http://api.census.gov/data/eits/marts
- http://api.census.gov/data/eits/mhs
- http://api.census.gov/data/eits/mrts
- http://api.census.gov/data/eits/mtis
- http://api.census.gov/data/eits/mwts
- http://api.census.gov/data/eits/qfr
- http://api.census.gov/data/eits/qpr
- http://api.census.gov/data/eits/qss
- http://api.census.gov/data/eits/qtax
- http://api.census.gov/data/eits/resconst
- http://api.census.gov/data/eits/ressales
- http://api.census.gov/data/eits/vip

These will be their new endpoint addresses:
- http://api.census.gov/data/timeseries/eits/ftd
- http://api.census.gov/data/timeseries/eits/hv
- http://api.census.gov/data/timeseries/eits/m3
- http://api.census.gov/data/timeseries/eits/marts
- http://api.census.gov/data/timeseries/eits/mhs
- http://api.census.gov/data/timeseries/eits/mrts
- http://api.census.gov/data/timeseries/eits/mtis
- http://api.census.gov/data/timeseries/eits/mwts
- http://api.census.gov/data/timeseries/eits/qfr
- http://api.census.gov/data/timeseries/eits/qpr
- http://api.census.gov/data/timeseries/eits/qss
- http://api.census.gov/data/timeseries/eits/qtax
- http://api.census.gov/data/timeseries/eits/resconst
- http://api.census.gov/data/timeseries/eits/ressales
- http://api.census.gov/data/timeseries/eits/vip

**Comment by loganpowell** [comment]
We're no longer aliasing Census API variables (in v2), so this issue can be closed.
