### ISSUE TITLE
Link to this repository on Census.gov is broken

### ISSUE THREAD

**Issue by SilverWingedSeraph** [uscensusbureau/citysdk#306]
There is a link to this repository on Census.gov at http://www.census.gov/developers/. However, its link is to https://github.com/uscensusbureau/citysdk.html, which is a 404, since the GitHub main page for repos does not carry a `.html` extension.

**Comment by logantpowell** [comment]
Hi @SilverWingedSeraph, Thank you for bringing this to our attention. We had some issues with link routing in our CMS that caused it to automatically add the ".html" to the end of links which had none. We've remedied the problem. Good catch and thanks again!
