### ISSUE TITLE
Does the API have 2015 ACS 5-year?

### ISSUE THREAD

**Issue by stevevance** [uscensusbureau/citysdk#316]
Is there a way to query the API for the latest available dataset?

The ACS 5-year for 2011-2015 is now available on American FactFinder.

**Comment by logantpowell** [comment]
Hi @stevevance,
It's available via API and therefore can be added to the SDK, but we are currently sans developer... want to submit a PR?

**Comment by stevevance** [comment]
I see a place for it here: https://github.com/uscensusbureau/citysdk/blob/master/citysdk.js#L442

````
var acs5 = { "2010": ["NAME"], "2011": ["NAME"], "2012": ["NAME"], "2013": ["NAME"], "2014": ["NAME"] };
````
Would it work just to add "2015" as another item in that object?

But there are lot of other tables in the `requiredVariables` object that might need to be updated:

**Comment by logantpowell** [comment]
I believe you are correct that the variable and year parameter will be referenced in multiple places

**Comment by stevevance** [comment]
@loganpowell I made the change to my own code to use 2015 ACS data, but now I see that you've archived that version and I haven't upgraded my project to use the new version (I tried, and it didn't work, and the version I'm using works well enough that it's not urgent to upgrade). 

For anyone still using the archived `citysdk.census.js` file, here's the code to change:

Line 23
````
CensusModule.prototype.DEFAULT_YEAR = 2015;
````

Line 35
````
CensusModule.prototype.acsyears = {
    "2010": ["acs5"],
    "2011": ["acs5"],
    "2012": ["acs5", "acs3", "acs1"],
    "2013": ["acs5", "acs3", "acs1"],
    "2014": ["acs5", "acs1"],
    "2015": ["acs5", "acs1"]
};
````
