### ISSUE TITLE
An API for units of measure and variable descriptions

### ISSUE THREAD

**Issue by hardnett** [uscensusbureau/citysdk#317]
This is to help with UIs that rely on CitySDK variables. There is a method that translates the internal variable names/codes to variable names. However, in some apps it will be useful to have the correct unit of measure and provide a short description of the data associated with a given variable. There are tables with this information as found here: [Census API Data](https://Api.census.gov/data.html )

Need: 

- Provide an API method that provides the units of measure of a data item/variable that can be queried by the variable name or census code.
- Provide an API method that provides access to a short description of each variable using the variable name or census code.

**Comment by logantpowell** [comment]
Just a note for future clarity: The "variable names" are referring to the [labels](http://api.census.gov/data/1990/pep/int_charagegroups/variables.html) available on api.census.gov/data.html (discovery tool)

**Comment by hardnett** [comment]
Yes. They are usually in the *Name* column. However, when we are writing code we use the codes like *B01003_001E*. So I am calling *B01003_001E* a code and those translate values like *commute_time* as a variable. Because I was thinking that these were correlated to the *Name* column in the discovery tool.

**Comment by logantpowell** [comment]
Sorry, would you like both the "name" and the "label" available in the [variables](http://api.census.gov/data/1990/pep/int_charagegroups/variables.html) or just the "name"?

**Comment by hardnett** [comment]
Sorry for the delay Logan. But here is an example of what we put in our code to help with the problem:
```
cmv.CENSUS_VARS = [
             {key: "B01002_002E", value: "median_male_age", title:"Median age -- Male"}, 
             {key: "B01002_003E", value: "median_female_age", title:"Median age -- Female"},
             {key: "B01003_001E", value: "population",  title:"Total Population"}, 
             {key: "B15003_002E", value: "education_none", title:"No Schooling Completed"}, 
             {key: "B15003_017E", value: "education_high_school", title:"Regular High School Diploma"},
             {key: "B15003_018E", value: "education_ged", title:"GED or Alternative Credential"},
             {key: "B15003_021E", value: "education_associates", title:"Associate's Degree"},
             {key: "B15003_022E", value: "education_bachelors", title:"Bachelor's Degree"}, 
             {key: "B15003_023E", value: "education_masters",  title:"Master's Degree"}, 
             {key: "B15003_024E", value: "education_professional", title:"Professional School Degree"}, 
             {key: "B17001_002E", value: "poverty", title:"Income in the Past 12 Months Below Poverty Level"}, 
             {key: "B19013_001E", value: "income", title:"Median Household Income in the Past 12 Months"}, 
             {key: "B19301_001E", value: "income_per_capita", title:"Per Capita Income in the Past 12 Months"}, 
             {key: "B23025_005E", value: "employment_unemployed", title:"In labor force: Civilian labor force: Unemployed"}, 
             {key: "B23025_007E", value: "employment_not_labor_force", title:"Not in labor force"}, 
             {key: "B08136_001E", value: "commute_time", title:"Aggregate Travel Time to Work (Minutes)"}, 
             {key: "B08136_004E", value: "commute_time_carpool", title:"Car, truck, or van: Carpooled (Minutes)"}, 
             {key: "B08136_007E", value: "commute_time_public_transport", title:"Public transportation (excluding taxicab) (Minutes)"},
             {key: "B08136_003E", value: "commute_time_solo_automobile", title:"Car, truck, or van: Drove alone (Minutes)"} 
    ];
  ```

The internal values of the CitySDK are "key" and "value" and what we added was "title" based on the variable specs you shared (http://api.census.gov/data/2015/acs5/variables.html). The "title" value typically came from the "Label" column, but in the case of determining the unit of measurements like "minutes" I had to get it from the "Concept" column.

**Comment by loganpowell** [comment]
Though not built into the CitySDK yet you can get these from the json endpoint, e.g.:
https://api.census.gov/data/2015/acs/acs5/variables.json

closing for now. Will reopen if sufficient interest in including feature arises
