### ISSUE TITLE
Local and Remote Data Access Load Balancing

### ISSUE THREAD

**Issue by hardnett** [uscensusbureau/citysdk#318]
Since it is possible to download the data and store it locally within an application, it would be nice to have the ability to access local data when available and then access the web service when a local version is not available. 

Need: Add functionality to the CitySDK to enable a developer to perform load balancing of data access. This would allow the developer to access local data when available instead of always loading from CitySDK.

**Comment by loganpowell** [comment]
Hi @hardnett we've released a new version (beta), which is now an NPM library, so you should now be able to do this. Let us know if you run into any problems.
