### ISSUE TITLE
Feature request: Ability to get block groups for a state

### ISSUE THREAD

**Issue by oliviaguest** [uscensusbureau/citysdk#319]
Hi All,

So as you might know I have been trying to get all the block groups for a state in the ASC5 census (thanks to @logantpowell for all the help btw!) but the server seems to hang for big (enough?) states. So instead Logan came up with the idea of cycling through the counties within a state to then get the block groups per county.

I wrote some code for doing so just today — I hope this makes sense to you and is a little useful! The repo has code that does both methods (the one that crashes on big states, and the one that works for all states) for Rhode Island (a little state so no crashing) to demonstrate that my technique (based on Logan's ideas) gives equivalent but not identical files to the way that makes the server hang (by asking for all the block groups within a state). Here is a repo with all the required code (please add your own API key): https://github.com/oliviaguest/get-block-groups 

Is it possible to make an official feature request for doing the above without having to write all that code to help future API users? :smile: 

Thanks again!
Olivia

**Comment by oliviaguest** [comment]
PS: Apologies if you are using Python 3. :angel:

**Comment by oliviaguest** [comment]
_Update_: Unfortunately this method doesn't work as the server times out when I ask for a state by counties too in some cases! For example, for state AK the server replies with 504 when I ask for the counties.

**Comment by loganpowell** [comment]
Hi @oliviaguest !

We've got a new version of CitySDK ready for open beta testing if you'd like to give it a go. It's an NPM library now, so it should work on your Node server or in the browswer (via Browserify, Webpack, etc.).

As for this issue, the primary culprit for the performance problem was that - before v2 of the CitySDK - we were tapping into full resolution (non-generalized) geographic boundary files. With v2, we've switched to cartographic boundary files and have converted them to GeoJSON for ease of use.

If you'd like to give it a go, please do! Let us know if you run into any issues as it's an early release (beta).

Hope you're doing well!

**Comment by oliviaguest** [comment]
Hi @loganpowell — I will keep you in the loop if I try this out. And thank you for everything — hope you are well too! :smile:
