### ISSUE TITLE
Demos using Leaflet

### ISSUE THREAD

**Issue by afrasier-bah** [uscensusbureau/citysdk#32]
When creating demos, use a variety of different libraries to demonstrate how to use the SDK.

i.e.: Google Maps, Leaflet, etc. . .

**Comment by logantpowell** [comment]
Census Reporter might have some poachable stuff for this... they use leaflet:

http://censusreporter.tumblr.com/post/112435574469/more-ways-to-use-census-boundaries-on-your-slippy

**Comment by afrasier-bah** [comment]
This hasn't been pushed yet, so I've re-opened it.

**Comment by afrasier-bah** [comment]
Resolved by d93e83f38bd472ca10e9bc6d96b0960a16110398
