### ISSUE TITLE
Consecutive Null Response Error

### ISSUE THREAD

**Issue by NJTuley** [uscensusbureau/citysdk#320]
We are getting multiple consecutive null responses from the citysdk request when we do a request for data. Below is the console log file, whenever the words "ERROR HELLO" are printed, our code received a null response from the server.

Here is our code for detecting and printing the "ERROR HELLO" message:

let variablesArray = [];

		for(let i = 0; i < response.features.length; i++){
			let dataPoint = response.features[i].properties[convertedVariable];
			let colorValue;

			for(let j = 0; j < colors.length; j++)
				if(dataPoint >= intervals[j].lower && dataPoint < intervals[j].upper){
					colorValue = colors[j];
					break;
				}else
					colorValue = colors[colors.length - 1];

			variablesArray.push({value: dataPoint, color: colorValue});
		}

for(let i = 0; i < variablesArray.length; i++) {
            if (isNaN(variablesArray[i].value))
			{
                setTimeout(cmv.run());
                console.log("ERROR HELLO")
				return;
        	}
	}

and here is the log file with the "ERROR HELLO" statements (in this request, we got 10 null responses before we got a response with data values)
[empty_request_citysdk_log.txt](https://github.com/uscensusbureau/citysdk/files/945909/empty_request_citysdk_log.txt)

**Comment by logantpowell** [comment]
Looking into this now...

**Comment by loganpowell** [comment]
@NJTuley 

We've got a new version of CitySDK ready for open beta testing if you'd like to give it a go. It's an NPM library now, so it should work on your Node server or in the browswer (via Browserify, Webpack, etc.).

Sorry for the (very long) delay
