### ISSUE TITLE
dev Roadmap? 

### ISSUE THREAD

**Issue by immexerxez** [uscensusbureau/citysdk#322]
Awesome project and a great idea however it doesn't seem that active anymore. Are there plans or a road map to get this to production or is it kinda just been put on hold for now?

**Comment by loganpowell** [comment]
Hi @immexerxez You are correct that the project is currently not in active development due to current budgetary constraints, but we fully intend on getting it back on its feet once resources become available. So, in short, yes - it's been put on hold for now.

**Comment by immexerxez** [comment]
@loganpowell thanks for the response. Seems like projects with huge potential are always the first to go with budget cuts. Hopefully it can all be resolved soon.
