### ISSUE TITLE
Cannot read property 'getContainerGeometry' of undefined

### ISSUE THREAD

**Issue by Dhavalptel** [uscensusbureau/citysdk#325]
I am getting Cannot read property 'getContainerGeometry' of undefined in this example https://uscensusbureau.github.io/citysdk/examples-v2/#/income-and-population#map-content

**Comment by loganpowell** [comment]
the problem is probably this:
``` html
<script src="https://s3.amazonaws.com/citysdk/releases/0.2.0/citysdk.js"></script>
```
the CitySDK is no longer hosted due to Commerce Data Service (the host) [dissolving along with its parent, ESA](http://community.amstat.org/blogs/steve-pierson/2017/03/16/fy18-statistical-agency-budget-developments) as a result of decisions made by the administration.
