### ISSUE TITLE
Proposal: Move Api to seperate project

### ISSUE THREAD

**Issue by Loag** [uscensusbureau/citysdk#327]
I think it'd breathe new life into the project & it would be much more manageable/maintainable in the long run.

**Comment by loganpowell** [comment]
Hi @Loag is your name Logan too? 

We've got a new version of CitySDK ready for open beta testing if you'd like to give it a go. It's an NPM library now, so it should work on your Node server or in the browswer (via Browserify, Webpack, etc.).

Give it a go and let us know what you think or if you run into any issues using it.
