### ISSUE TITLE
'shadow is not defined' error on import

### ISSUE THREAD

**Issue by kuramameng** [uscensusbureau/citysdk#329]
Uncaught ReferenceError: shadow is not defined
    at Object.eval (census.js?64d9:831)
    at eval (census.js?64d9:3)
    at Object.eval (census.js?64d9:9)
    at eval (census.js:833)
    at Object../node_modules/citysdk/census.js (app.js:4188)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js&:3)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js& (app.js:4130)
    at __webpack_require__ (app.js:725)

Didn't see 'shadow-cljs' dependency in the package.json. I don't think it is required either. Any help on this is appreciated.

**Comment by loganpowell** [comment]
@kuramameng at what point in the process did you encounter this error?

**Comment by loganpowell** [comment]
Can you share a code snippet?

**Comment by kuramameng** [comment]
Thanks for looking into this so quickly. This error occurs as soon as `import census from 'citysdk'` is called. I am also using `yarn` instead of `npm`, not sure if that matters or not. 

Here's a simple code snippet, it is nothing but a simple vue template with the import:
```
<template>
  <b-container fluid>
  </b-container>
</template>

<script>
import census from 'citysdk'

export default {
  name: 'search',
  data () {
    return { }
  }
}
</script>
```

My package.json:
```
{
  "name": "vue_app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "postinstall": "yarn build"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.13",
    "citysdk": "^2.0.7",
    "leaflet": "^1.4.0",
    "lodash": "^4.17.11",
    "vue": "^2.5.13",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.6",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.6",
    "@vue/cli-service": "^3.0.0-beta.6",
    "@vue/eslint-config-standard": "^3.0.0-beta.6",
    "lint-staged": "^6.0.0",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13"
  },
  "babel": {
    "presets": [
      "@vue/app"
    ]
  },
  "eslintConfig": {
    "root": true,
    "extends": [
      "plugin:vue/essential",
      "@vue/standard"
    ]
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.js": [
      "vue-cli-service lint",
      "git add"
    ],
    "*.vue": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}

```

**Comment by loganpowell** [comment]
@kuramameng I've updated my packager, which might help this issue. Please `npm update citysdk` and let me know if that helps.

**Comment by kuramameng** [comment]
yup, upgrading citysdk worked. Thanks again for the help.
