### ISSUE TITLE
Get population by Zipcode

### ISSUE THREAD

**Issue by vuchau** [uscensusbureau/citysdk#330]
We can extract population with Zip code ? E.g 10036

**Comment by loganpowell** [comment]
Kind of. The Census Bureau uses an approximation of Zip Code called "Zipcode Tabulation Areas". Have a look at [the example in the README](https://github.com/uscensusbureau/citysdk#notable-example-1). 

Are you just looking for statistics or are you also looking for geographic boundaries?

**Comment by vuchau** [comment]
> Kind of. The Census Bureau uses an approximation of Zip Code called `"zip-code-tabulation-area" `. Have a look at [the example in the README](https://github.com/uscensusbureau/citysdk#notable-example-1).
> 
> Are you just looking for statistics or are you also looking for geographic boundaries?

@loganpowell thanks for your comment. I tried but the returned data did not match my expectations.
I just want to find the total population of a postal_code. 
I've obtained the population of contry, place, city based on lat / long with sample.
`census(
        {
          vintage: 2017,
          geoHierarchy: { place: { lat: lat, lng: lng } },
          sourcePath: ["pep", "population"],
          values: ["POP"], 
          statsKey: "xxxx"
        },(err, resp) => {
         console.log(resp);
        }
      );`
Could you give me an advice? Thanks

**Comment by loganpowell** [comment]
If you just want the population, try this:
```js
census({
    "vintage" : "2017",
    "geoHierarchy" : {
      "zip-code-tabulation-area" : "22202" // whatever zipcode
    },
    "sourcePath" : ["acs", "acs5"],  
    "values" : ["B01001_001E"]  // Total population
  }, (e, r) => console.log(r)
)
```

**Comment by vuchau** [comment]
> If you just want the population, try this:
> 
> ```js
> census({
>     "vintage" : "2017",
>     "geoHierarchy" : {
>       "zip-code-tabulation-area" : "22202" // whatever zipcode
>     },
>     "sourcePath" : ["acs", "acs5"],  
>     "values" : ["B01001_001E"]  // Total population
>   }, (e, r) => console.log(r)
> )
> ```
@loganpowell. It's work fine. Thanks so much.
