### ISSUE TITLE
Cryptic errors

### ISSUE THREAD

**Issue by lyatziv** [uscensusbureau/citysdk#333]
I'm seeing this error with the following parameters and I'm unsure what the error is asking for in terms of the `nation-level` and `state-levels`.
```
{
  "vintage": 2018,
  "geoHierarchy": {
    "consolidated cities": "*"
  },
  "geoResolution": "500k"
}
```
Returns
```
"For 'consolidated cities' try of of the following:"
"=== :us = nation-level 'consolidated cities' geoResolutions ==="
"=== :st = state-levels 'consolidated cities' geoResolutions ==="
```

**Comment by loganpowell** [comment]
You're not getting anything under the `"=== :st = state-levels 'consolidated cities' geoResolutions ==="` line?

Consolidated cities are only available at the State level. You can either specify a state FIPS code or use the geocoding feature:

option 1:
```
{
  "vintage": 2018,
  "geoHierarchy": {
    "state": "21", // FIPS code for KY
    "consolidated cities": "*"
  },
  "geoResolution": "500k"
}
```
or option 2:
```js
{
  "vintage": 2018,
  "geoHierarchy": {
    "state" : {
      "lat": <latitude>,
      "lng": <longitude>
    },
    "consolidated cities": "*"
  },
  "geoResolution": "500k"
}
```

**Comment by loganpowell** [comment]
Just not that not all states have Consolidated Cities

**Comment by lyatziv** [comment]
> You're not getting anything under the "=== :st = state-levels 'consolidated cities' geoResolutions ===" line?
I do. It's...
```
[:2018 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2017 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2016 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2015 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2014 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2013 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2010 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2000 {:us ["500k"], :st nil}]
```

I was hoping for a single API call to get all `Consolidated Cities`, given that the following is acceptable

```
{
  "vintage": 2018,
  "geoHierarchy": {
    "metropolitan statistical area/micropolitan statistical area": "*"
  },
  "geoResolution": "500k"
}
```

**Comment by loganpowell** [comment]
Ah, good, yes, well what this is saying:
```clj
[:2018 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2017 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2016 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2015 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2014 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2013 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2010 {:us nil, :st ["500k"]}]
citysdk.js:1 [:2000 {:us ["500k"], :st nil}]
```
is that the geojson is only available at the `:st` (state) level and at the `500k` resolution

MSAs are stored at the national level, that's why it's simpler to get them.

You can create an array of state fips codes and just make the call for all of them and merge/concatenate the results if you need all of them

**Comment by loganpowell** [comment]
Here's a list to help you out: 

https://github.com/uscensusbureau/citysdk/blob/master/v2/src/census/geoAPI/states.cljc

**Comment by lyatziv** [comment]
Weird flex but ok...
