### ISSUE TITLE
2.0.34 response is "Unsuccessful: configuration request"

### ISSUE THREAD

**Issue by tobinbradley** [uscensusbureau/citysdk#334]
Using citysdk 2.0.34, every request I try, including ones straight from the README, the response returns "Unsuccessful: configuration request". I'm getting this in the browser and via NodeJS. Ex:

```javascript
const census = require('citysdk')

census({
    "vintage" : 2015,    // required
    "geoHierarchy" : {   // required
      "county" : {
        "lat" : 28.2639, 
        "lng" : -80.7214
      }
    }
  }, 
  (err, res) => console.log(res)
)
```

```html
<script src="./citysdk.js"></script>
<script>
  census({
      "vintage": 2015,    // required
      "geoHierarchy": {   // required
        "county": {
          "lat": 28.2639,
          "lng": -80.7214
        }
      }
    },
      (err, res) => console.log(res)
    )
</script>
```
I downgraded citysdk to 2.0.0 and things start working in Node. I haven't worked my way back up the release tree to see where things went awry, but 2.0.20 works, and 2.0.33 gives the same unsuccessful configuration message. 

Just wanted to let you know. Thanks for your work on this project!

**Comment by loganpowell** [comment]
let me fix this... give me 20 minutes

**Comment by loganpowell** [comment]
Can you give `npm update` a try (v 2.0.35) and let me know if it works...

**Comment by tobinbradley** [comment]
That did the trick. Thanks!
