### ISSUE TITLE
Slack community invite link broken

### ISSUE THREAD

**Issue by VivekNair** [uscensusbureau/citysdk#336]
Hey team,

Wasn't sure about the best place to report this, but the Slack community invitation link seems to be broken:

https://www.census.gov/developers/

Would love to get into the community and start asking questions.

Best,
Vivek

**Comment by loganpowell** [comment]
Hi @VivekNair thank you for bringing this to our attention> I will get that fixed, but [here is the link](https://join.slack.com/t/uscensusbureau/shared_invite/enQtNzI2MTY0NjA4MzU1LTYxOGE1YTVmMmU2ZjM5MjE0Yzk1NTg5Yjk4NTMxMzhhM2RjMGU5ZDMxMDgxMzMyOThiMTVlZDE0Y2ZiMjQzYjM)

**Comment by VivekNair** [comment]
Thanks - worked like a charm

**Comment by loganpowell** [comment]
fixed
