### ISSUE TITLE
2010 Geocoding Broken

### ISSUE THREAD

**Issue by chase-adams** [uscensusbureau/citysdk#347]
The following code breaks the geocoding results:

```
census(
  {
    vintage: 2010,
    geoHierarchy: {
      // required
      state: {
        lat: 37.774929,
        lng: -122.419418,
      },
    },
    sourcePath: ['dec', 'sf1'],
    values: ['NAME', 'B25001_001E'],
  },
  (err, res) => console.log({ err, res }),
)
```

The code makes an attempted request to:
https://tigerweb.geo.census.gov/arcgis/rest/services/Census2020/tigerWMS_Census2010/MapServer/98/query?geometry=-122.419418,37.774929&geometryType=esriGeometryPoint&inSR=4269&spatialRel=esriSpatialRelIntersects&returnGeometry=false&f=pjson&outFields=STATE

This request results in an error from the TigerWeb server.

**Comment by loganpowell** [comment]
Looks like those layers were moved [here](https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb).

Let me see if I can reconfigure this for you today.

**Comment by chase-adams** [comment]
Thank you! I appreciate it. Hopefully those layers don't shift in the future 🤞

**Comment by loganpowell** [comment]
can you update to `2.2.0` and see if that fixes it for you?

**Comment by chase-adams** [comment]
That fixed it - thank you @loganpowell! FYI here is the upstream project:

https://github.com/smartcontractkit/external-adapters-js/pull/1098

**Comment by loganpowell** [comment]
Thank you for the report
