### ISSUE TITLE
Print Census API errors in the error object

### ISSUE THREAD

**Issue by allthesignals** [uscensusbureau/citysdk#349]
Hi! My request fails because I'm asking for too many variables:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/5004319/172023164-4156621c-ad74-4731-9d2c-cb5521a1771c.png">

Instead, it says "Unsuccessful: Census statistics request". It'd help to include the error response from Census API.

A new feature might be something that splits up a large number of calls (50+ variables) into multiple batch requests...

**Comment by loganpowell** [comment]
Hi @allthesignals! Sorry for the delayed response. I will look into trying to pass the error returned from the Census stats API through CitySDK.

**Comment by loganpowell** [comment]
Closing this as resolved. Let me know if you have any trouble with it.
