### ISSUE TITLE
Refactor Census API data to conform to module architecture

### ISSUE THREAD

**Issue by afrasier-bah** [uscensusbureau/citysdk#36]
We need to refactor the Census API into its own module, out of the CitySDK core.

**Comment by logantpowell** [comment]
@afrasier-bah @JoeGermuska @lgangas @jmeisel This could be an opportunity to integrate with the [Census Reporter](https://github.com/censusreporter) project

**Comment by afrasier-bah** [comment]
Resolved by d93e83f38bd472ca10e9bc6d96b0960a16110398
