### ISSUE TITLE
Integrate Dept of Labor APIs into City SDK:  BLS APIs, ONET, CareerOneStop 

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#42]
Per Dept of Labor SME:  O*NET, CareerOneStop and BLS APIs are routinely integrated into consumer apps. I would register a CitySDK account for access to O*NET and CareerOneStop, it takes a day or two to get access approved. When it comes to the raw data, most of the BLS data is download-able.

**Comment by jmeisel** [comment]
Clarification of priorities:
1.  BLS API - high-level employment data
2.  Career OneStop - granular (ex: wages based on industry)
3.  ONET - occupation

**Comment by afrasier-bah** [comment]
Do one of the three, whichever has proper API implementation.

**Comment by afrasier-bah** [comment]
BLS API doesn't support CORS
Career OneStop and ONET have API registration which needs review.

**Comment by tyronegrandison** [comment]
Can you point me to the documentation that outlines why CORS is necessary? I have brought up the issues with the BLS and ETA.  

On COS and ONET are the agreements going through Legal?  Or is the issue that the CitySDK platform would have to get accounts to use it.

**Comment by afrasier-bah** [comment]
CORS (or JSONP support) is necessary because we are using JavaScript ajax calls to load the data from the APIs, without CORS or JSONP we'd need to implement a proxy within the SDK which we'd like to avoid as it complicates the user experience.

COS and ONET just means users would need to get accounts. I wasn't sure how long it would take them to get approved but it only took a day or so.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
