### ISSUE TITLE
Re-factor "Detailed Economic Window" demo using City SDK and BLS dataset

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#43]
This demonstration has already been created using Census Reporter and BLS data.  It was a winner of the District Data Labs Incubator program http://dew.herokuapp.com

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
