### ISSUE TITLE
Local data use-case:  Integrate Building Permit Data

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#44]
(feedback from Chief Innovation Officer of Montgomery County, Dan Hoffman)  Building permit data is one of the most cross-cutting local datasets utilized across multiple cities nationwide.

**Comment by afrasier-bah** [comment]
Implementation of #45

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
