### ISSUE TITLE
Support the ability to easily pull in data from commonly used open data platforms (Socrata)

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#45]
(feedback from Chief Innovation Officer of Montgomery County, Dan Hoffman) Socrata is commonly used to manage open data platforms for cities and should work easily with City SDK.

**Comment by afrasier-bah** [comment]
Research socrata

**Comment by ajturner** [comment]
check out [Koop](https://github.com/esri/Koop) - there is a [Koop-Socrata](https://github.com/koopjs/koop-socrata) adapter for reading from the API. There could then be a CitySDK adapter to make it easy to push/pull between these APIs.

Generally, Koop is an open-source Web API proxy. 

As a benefit, that would also make it easy to work with [GeoServices API](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Getting_started/02r3000000sq000000/) that is used for all ArcGIS powered APIs. 

/cc @ngoldman @chelm

**Comment by jmeisel** [comment]
Thanks for the suggestion Andrew - I've been wondering if there was a way to leverage Koop for this project.

**Comment by afrasier-bah** [comment]
Clarified into #56

**Comment by ajturner** [comment]
@afrasier-bah curious if that new issue resolved this issue, or is just a single task? There are a lot of open data APIs. Seems like a general solution would be useful.

**Comment by afrasier-bah** [comment]
Yeah - I'm going to build a general module to support, generally, all Socrata end points (making it easy to use their SODA2 variables like $where, $select, etc.)

**Comment by ajturner** [comment]
How about non-SODA API services? [ArcGIS Geoservices](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r3000000r1000000) have where select, extent, statistics, time, fields, etc. given it [powers TIGER web](http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Labels/MapServer/7) it may be relevant.

**Comment by logantpowell** [comment]
I'm gonna reopen this as we are changing the implementation and might benefit from a revisit.

**Comment by loganpowell** [comment]
Closing in favor of https://github.com/uscensusbureau/citysdk/issues/339
