### ISSUE TITLE
Are functions linked to existing data sets? 

### ISSUE THREAD

**Issue by mikelmaron** [uscensusbureau/citysdk#5]
http://uscensusbureau.github.io/citysdk/functions.html

looks like these would be covered by a mixture of city, state, federal, and company data sets / APIs?

**Comment by jmeisel** [comment]
Yes the functions will be linked to existing data sets from Census, HUD, Open City data, and other sources.   We are about to finalize our 1st dev sprint which will show these use-cases with more granularity, at which point I'll update with full details.

**Comment by mikelmaron** [comment]
To clarify, I would suggest making aggregate level an option. So you could say, give me zip code level at this location.  Another option might be whether return the results of higher aggregate areas as a GeoJSON GeometryCollection; or to return some kind of average across the aggregate areas.

**Comment by jmeisel** [comment]
Great - that makes sense.  Will add to the backlog.

**Comment by logantpowell** [comment]
Hi @mikelmaron, we are currently refactoring our entire code base (we are still very much in prototype phase) and will be coming back with a new architecture that will - hopefully - be easier to understand and use. Stay tuned and if after the update (approx. 1 month) you are not satisfied, please reopen an issue in response to the new structure.
