### ISSUE TITLE
Housing User Story: I want to know where public land to develop is?

### ISSUE THREAD

**Issue by connorjmcd** [uscensusbureau/citysdk#51]
Municipalities across jurisidictions (City, County, School District, etc.) often own land that could be developed for affordable housing or other social service purposes but they do not know what land they have nor what other juridictions may have.  Having this information visualized geographically would help juridictions work together on shared goals around creating affordable housing.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
