### ISSUE TITLE
Housing User Story: I want to visualize all my affordable housing options

### ISSUE THREAD

**Issue by connorjmcd** [uscensusbureau/citysdk#52]
There are locally and federally supported affordable housing but often these data sets are remote from each other.  How do we integrate local and federally affordable housing for city/county or state in one API?  Currently users ('those looking for affordable housing') go to numerous remote websites to find resources when they could be in one thread.

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
