### ISSUE TITLE
Geoservice Use-Case #1:  User sends a lon/lat coordinate and an entity type

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#53]
User sends a lon/lat coordinate and an entity type (limited to state, county, place (covers cities), tract, and block group). In return, the service provides the FIPS code and geometry of the entity containing the point received.  The entity is of the entity type requested.

**Comment by OpenGlobe** [comment]
So I like this - would a user be able go grab any associated geometries (block, tract, ZIP, etc.)?
