### ISSUE TITLE
Geoservice Use-Case #2: User sends a FIPS code and an entity type

### ISSUE THREAD

**Issue by jmeisel** [uscensusbureau/citysdk#54]
User sends a FIPS code and an entity type. In return, the service provides the FIPS codes and geometries for all the entities of the entity type requested within the FIPS code received.  For Places, some of the entities returned may cross the FIPS code's boundary.

**Comment by jmeisel** [comment]
From Jeff Chen (PIF at Nasa, former NYC data scientist):  Within the FIPS, how far down would you guys plan to go in terms of administrative boundaries? Would zips be included? Maybe add PUMAs (FIPS 2 digit for state + 3-digit PUMA id) as the ACS gets published with new data at that level and it'd be nice to tie that in. At least in NYC, the PUMA boundaries are somewhat similar to the council district areas.

**Comment by loganpowell** [comment]
we've got you and better with v2 on this. You can even send in just a coordinate (lat+lng) and v2 will handle the FIPS stuff for you ;)
