### ISSUE TITLE
Socrata Module

### ISSUE THREAD

**Issue by afrasier-bah** [uscensusbureau/citysdk#56]
As a developer, I would like a module that allows me to specify an API end point for a Socrata data portal, and use the SoQL variables via a json request.

**Comment by lgangas** [comment]
Ask Ian (CDO Dept of Commerce) - can Socrata help

**Comment by afrasier-bah** [comment]
Resolved by e9d4feafb6e9ce2645e7f1ed5f2abc828d3468da
