### ISSUE TITLE
Consider Code for America API work

### ISSUE THREAD

**Issue by mikelmaron** [uscensusbureau/citysdk#6]
http://census.codeforamerica.org/

**Comment by logantpowell** [comment]
I think we're covering this with  Issue #57

**Comment by logantpowell** [comment]
Thank you for this reference, @mikelmaron. Might you be able to connect us with these owners? Perhaps we could collaborate or at least have them tell us what they think of what we're up to as per their (and their users') needs?

**Comment by mikelmaron** [comment]
Sure -- @migurski!

**Comment by logantpowell** [comment]
@migurski might you have some time to sync up on this next week?

**Comment by migurski** [comment]
Hey @logantpowell, sure. How about here in the comments?

**Comment by logantpowell** [comment]
Alrighty... what do you think of the CitySDK?

**Comment by migurski** [comment]
Looks neat! It sounds like a web-based API for retrieving census data?

**Comment by logantpowell** [comment]
There's both a JavaScript SDK and a Node API currently. Our man @tshrestha has led the Node dev and has been harmonizing it with a new version of the SDK. But, to your point, it is essentially a proxy built on top of three Census APIs:
- [Geocoder](http://geocoding.geo.census.gov/): handles addresses and turns them into lat/lngs
- [TigerWeb](https://tigerweb.geo.census.gov/tigerwebmain/TIGERweb_restmapservice.html): serves up Census boundaries (geographic areas/shapes)
- [DataWeb](http://www.census.gov/developers/): serves up Census statistics (growing all the time)

The CitySDK also incorporates [terraformer](http://terraformer.io/) which allows us to do some cool stuff with a user's own geographic boundaries ([and other cool stuff](http://terraformer.io/core/#terraformerprimitive)).

Essentially, it helps developers and researchers build maps with Census data ;)

**Comment by migurski** [comment]
That’s great! As a latecomer to this issue, is there something about the CfA work above that might be useful here?

**Comment by logantpowell** [comment]
Let us know if there's anything that you would find useful for us to add to accommodate your needs?
