### ISSUE TITLE
Incorporate Census Reporter Glossary

### ISSUE THREAD

**Issue by afrasier-bah** [uscensusbureau/citysdk#62]
Add a glossary for variables to the Census module.

**Comment by JoeGermuska** [comment]
Happy to discuss if there's a way Census Reporter can make this work better or improve interop. I'm pretty keen on the solution we have but it's very just-as-much-as-needed-to-function, and we never thought about others using it.

**Comment by afrasier-bah** [comment]
Thanks Joe! For the current iteration I'm just going to make a very simple solution based on the Census's large ACS variable json, but the Reporter is the inspiration and eventually the goal :)

**Comment by afrasier-bah** [comment]
Resolved 97d7c58cbd3c958c4314599b9e431a7ab3a86935
