### ISSUE TITLE
Add City-Focused datasets from Digital Services Center

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#63]
http://digitalservicescenter.com/

**Comment by tyronegrandison** [comment]
More information on DSC https://github.com/abhinemani/digitalservicescenter and https://medium.com/@abhinemani/small-city-pieces-loosely-joined-5202fb5a93e3

**Comment by lgangas** [comment]
Arman - can you compare this vs Socrata modules? what is the estimated level of effort to fork this/integrate this?

**Comment by loganpowell** [comment]
Closing in favor of https://github.com/uscensusbureau/citysdk/issues/339
