### ISSUE TITLE
help wanted: Python wrapper for CitySDK

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#65]

**Comment by lgangas** [comment]
Arman to estimate level of effort this

**Comment by copelco** [comment]
I'm interested in this too!

**Comment by logantpowell** [comment]
We have put in a request for an API management platform that would allow us to automate (to some degree) the production of SDKs for various languages given our new [Node API](https://github.com/uscensusbureau/citysdk/blob/master/src/api/README.md). However, that request will take some time to deliver.

In the meantime, you might want to check out Sunlight Lab's [Census Python wrapper](https://github.com/sunlightlabs/census). I would encourage you to contribute to that project to suit your immediate needs.
