### ISSUE TITLE
help wanted: Ruby wrapper for CitySDK

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#66]

**Comment by logantpowell** [comment]
We're moving all the add-on SDK requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of an SDK for a specific language/platform:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/sdk-requests.csv]
