### ISSUE TITLE
User Story: Utilize Census Data to identify communities of interest related to the Every Kid in a Park

### ISSUE THREAD

**Issue by OpenGlobe** [uscensusbureau/citysdk#7]
Utilizing Census data, can we better identify communities of interest related to the Every Kid in a Park Initiative?  Can we frame this as a session for the upcoming myAmerica Developer Summit?  See http://openglobe.github.io/myamerica-devsummit/#sessions

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
