### ISSUE TITLE
Add Google Analytics - for github io page

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#71]

**Comment by tyronegrandison** [comment]
Is this being handled by @jmeisel or @logantpowell ? Will it be in this sprint?

**Comment by lgangas** [comment]
I registered the site in google analytics - just need to drop in script....

On Thu, May 28, 2015 at 10:45 PM, Tyrone Grandison <notifications@github.com
> wrote:

> Is this being handled by @jmeisel <https://github.com/jmeisel> or
> @logantpowell <https://github.com/logantpowell> ? Will it be in this
> sprint?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uscensusbureau/citysdk/issues/71#issuecomment-106663856>
> .
>



-- 
~Live ~ Love ~ Learn

**Comment by lgangas** [comment]
dropped in script to all pages
