### ISSUE TITLE
Investigate using api.data.gov for supporting data without CORS headers (18F)

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#78]

**Comment by afrasier-bah** [comment]
api.data.gov has CORS enabled (yay), and it looks as though it is fairly simple for agencies to integrate with data.gov; however, the impetus is entirely on the agency. That is, if we want to use (for example) DOL BLS data, they DOL will have to contact data.gov about integrating their dataset.

**Comment by afrasier-bah** [comment]
Resolved by e9d4feafb6e9ce2645e7f1ed5f2abc828d3468da
