### ISSUE TITLE
Integrate Maine-specific issues

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#79]
Maine has traditionally focused on Transportation concerns, e,g, bus tracking.

They are moving towards Regional economic issues.  They want to develop solutions at the intersection of Economics, Marine and Citizen Science.

The CfA Maine has the following pages

https://www.codeformaine.org/dashboard/
https://github.com/Code4Maine/

**Comment by logantpowell** [comment]
We're moving all the add-on dataset/module requests to table so folks can see all of them in the same place, add to them (via pull request) and/or volunteer to take ownership over the development of a module for one:

Check out the table (here)[https://github.com/uscensusbureau/citysdk/blob/master/issues/datasets-requests.csv}
