### ISSUE TITLE
Investigate DAT as a way to sync and distribute data sets

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#80]
http://dat-data.com/docs.html

Use cases https://github.com/maxogden/dat/labels/use%20case

**Comment by JoeGermuska** [comment]
seems out of scope for citysdk itself. Not that it's a bad idea.

**Comment by tyronegrandison** [comment]
It was not intended to be a feature for the MVP. The idea was that in order to ensure synchronized integration and versioning of city-level data, there would need to be a tool, such as DAT. This issue is to bring up the point of ensuring a coherent technical strategy for data.

**Comment by logantpowell** [comment]
We have looked into this and determined that DAT is not well suited for CitySDK's needs.
