### ISSUE TITLE
Admin for configuring smart alias based on geography

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#81]
Per Nancy's feedback, need to be able to provide back best income per user selected geography level. Choose most accurate variable chosen by geography level selected

**Comment by lgangas** [comment]
Logan - can you see if there's a census tutorial on this api.   Arman confirmed that the Census APIs return the median income by appropriate geography level already. We need to just capture the documentation better.

**Comment by logantpowell** [comment]
@lgangas I'm not sure what you're asking me to do here... I'm not aware of an API that accommodates this capability.
