### ISSUE TITLE
user documentation integrated natively in github io pages (focused on user interface)

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#83]

**Comment by jmeisel** [comment]
Add more examples in the spirit of the showcase.  Key areas to focus:
- interactively try functions
- continue to build out showcase

**Comment by lgangas** [comment]
find a way to show how to integrate other datasets

**Comment by afrasier-bah** [comment]
Completed for this sprint by bd03044eb79444e6fde16937701512215dc59b3c
