### ISSUE TITLE
translation or cross walking services

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#84]
Would be useful to developers 

Zip to FIPS   http://www.huduser.org/portal/datasets/usps_crosswalk.html

**Comment by afrasier-bah** [comment]
There's actually already a zip->fips service internally for the Census. There was talk of opening it up to the public (and thus, CitySDK) but I'm not sure where that discussion went. I'll inquire.

**Comment by tyronegrandison** [comment]
Please do. This would be an awesome WIN.

**Comment by afrasier** [comment]
Resolved via #86
