### ISSUE TITLE
Consistent use of brand

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#87]
It has been referred to as "citysdk", "city sdk", "city SDK", we should pick a single representative and stick with it. 

I suggest changing all references to "CitySDK"

**Comment by lgangas** [comment]
Which file did u edit? index?

**Comment by tyronegrandison** [comment]
The settings on the github repo main page https://github.com/uscensusbureau/citysdk/

Changed everything back. However, figured I broke a link when I initially changed citysdk to CitySDK

**Comment by tyronegrandison** [comment]
https://uscensusbureau.github.io/citysdk no longer works

**Comment by afrasier-bah** [comment]
I fixed it. gh-pages is case sensitive, when you changed the repository name it broke all of it.
I think the repository name can stay all lower case as that is pretty much the convention for repository names.

**Comment by tyronegrandison** [comment]
Thanks Arman. I figure that was the case (afterwards)

**Comment by philipashlock** [comment]
Over the past few weeks I've been reminded of the importance of #88 and not only the issue of findability with search engines but genuine confusion between this and the original @CitySDK which is still mentioned often, e.g. within the [Open and Agile Smart Cities](http://connectedsmartcities.eu/open-agile-smart-cities/) and [FIWARE](https://www.fiware.org/smart-cities/) work and at the NIST Global Cities event on Monday: 

![cgb0zvvw8aemk7p jpg_large](https://cloud.githubusercontent.com/assets/183402/7965688/18e9ab7e-09ed-11e5-9c62-e958f14f1cdc.jpeg)

Perhaps it's worth considering a different name or clarifying the branding strategy with the original CitySDK folks?

**Comment by jmeisel** [comment]
Good and important feedback.  I don't have an immediate answer but it needs addressed.  We want to compliment EU team, they are doing great work.
