### ISSUE TITLE
Define a core "Interface" definition for the API

### ISSUE THREAD

**Issue by ajturner** [uscensusbureau/citysdk#90]
The vision of CitySDK (both US and EU models) is to provide a common, simple and reusable programming interface to data provided from any agency or government entity. The benefit is that developers can write code once that is easily reused for different geographic regions or different applications.

For example - if an application allows the user to draw a polygon on a map and have it summarize population and house loan funding from HUD - can they change to compare population with air quality from EPA by only changing the source and the summarized attribute variable?
## Interface Definition

Evaluate the 'least common denominator' functions and input parameters. These would be common across (nearly) all APIs. Then designate the provider specific parameters. 
### Methods
- **query(parameters)** calls the API and returns an object including an array of features.
- **variables()** returns an array of the attributes that the source supports

_others?_
### Parameters
- **Module** API or agency - already designated by the Module itself: `census.query()` vs. `hud.query()`
- **Source** most API will have a catalog of data sources within their CitySDK adapter. _e.g._ `{'source': 'ACS2013'}`, `{'source': 'FHA Loans'}`
- **Variables** within the source, developers likely only want a subset of the available attributes. _e.g._ `{'variables': ['income','population']}`, `{'variable': ['Loan Count','Unpaid Balance']}`
- **Location** Location (Point or Polygon)
- **Filters** Source specific filters such as `['population > 1000000','population < 4000000']`

_others?_

/cc @jmeisel @afrasier-bah

**Comment by tyronegrandison** [comment]
+1 to this.

**Comment by jmeisel** [comment]
+1

This is needed to scale our ability to get partners to plug in, while keeping it simple for end user of the sdk.

**Comment by tyronegrandison** [comment]
There was mention of the need to do arithmetic operations on one or more parameters. Is this a separate issue?
@afrasier @jmeisel @lgangas @logantpowell

**Comment by ajturner** [comment]
IMO that is a different issue.

**Comment by loganpowell** [comment]
check out the new options in v2.
