### ISSUE TITLE
ACS Age returns wrong data

### ISSUE THREAD

**Issue by ajturner** [uscensusbureau/citysdk#92]
Run the [ArcGIS GeoEnrichment Demo](http://esridc.github.io/citysdk-arcgis/start.html#) - Age values are `2325`, `944`, etc.

![citysdk-arcgis](https://cloud.githubusercontent.com/assets/1218/7717896/eaedaa08-fe76-11e4-8165-8f8140d4e3b1.png)

/cc @afrasier-bah @jmeisel

**Comment by afrasier-bah** [comment]
This is largely due to the fact that we need to update a few of the alias variables. We should be in contact with an ACS expert to improve these - what would you expect from an "age" call? I'd assume the average age for the specified location, but please correct me if I'm wrong!

**Comment by ajturner** [comment]
I would refer to the [ACS Subject Definitions (PDF)](http://www.census.gov/acs/www/Downloads/data_documentation/SubjectDefinitions/2013_ACSSubjectDefinitions.pdf). 

Specifically page 49 says `Median Age`. 

Generally seems wise to align with those standard names as then the descriptions could be used for the metadata or any users/devs that have questions.

**Comment by afrasier** [comment]
I've updated it from what it was to B01002_001E (Median Age by Sex - Total) which is what one would expect. It will be out in the next push from the Census internal repo.

**Comment by ajturner** [comment]
@afrasier :+1:

**Comment by afrasier** [comment]
Resolved f1cabdf45be7797e9b3266c39a6b0db60db7549e but note #113 when updating code. Documentation will be updated today regarding that.
