### ISSUE TITLE
ACS Commute times return wrong data

### ISSUE THREAD

**Issue by ajturner** [uscensusbureau/citysdk#93]
Visit [ArcGIS Demo](http://esridc.github.io/citysdk-arcgis/start.html#) and choose `Commute Time`. Often are null or values like `37205`. 

![citysdk-arcgis](https://cloud.githubusercontent.com/assets/1218/7717904/0d6724d8-fe77-11e4-9068-fc587144cd0b.png)

/cc @afrasier-bah @jmeisel 
related #92

**Comment by afrasier** [comment]
Unfortunately this isn't an error with the SDK, but rather with the ACS. For commute times there are a lot of areas (especially as you get below the county level) that simply didn't report commute times or don't have that data available. This is why there are so many null values.

Second, the number is in minutes per person per day. The commute time variable is marked as normalizable in the alias dictionary, so the SDK will also return a "commute_time_normalized" variable which divides the commute time by the population for the region requested. 

Still working on improving documentation on these sorts of things! I hope this helps.
