### ISSUE TITLE
find a way to search/find for variables easier

### ISSUE THREAD

**Issue by lgangas** [uscensusbureau/citysdk#94]
ala wikipedia for submit documentation for variables

**Comment by logantpowell** [comment]
From our friends at Census Reporter (ACS) http://www2.census.gov/acs2013_5yr/summaryfile/Sequence_Number_and_Table_Number_Lookup.xls

**Comment by lgangas** [comment]
folding into #100

**Comment by johnson-tor-boozallen** [comment]
Closing as this has been folded into #100
