### ISSUE TITLE
A well-documented example showing how to leverage Esri Business Analyst Online for a specific City, CENSUS data and visualize it using D3.

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#95]

**Comment by tyronegrandison** [comment]
I think ESRi refers to the Business Analyst Online (BAO) data as GeoEnrichment. 

I would also that each of these examples focus on a (diffferent) specific industry vector.

**Comment by jmeisel** [comment]
+1 maybe Andrew can build this guide?

**Comment by afrasier** [comment]
Tagging the glorious Mr. Turner
/cc @ajturner

**Comment by loganpowell** [comment]
D3 examples with source code can be found here:

https://uscensusbureau.github.io/citysdk/examples/#d3js
