### ISSUE TITLE
A well-documented example for a City using Socrata data, CENSUS data and visualize it using another viz not D3 

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#96]

**Comment by tyronegrandison** [comment]
Using Chicago data, Crime (https://data.cityofchicago.org/view/5cd6-ry5g), Traffic Violations (Red Light Camera Violations https://data.cityofchicago.org/view/caas-knxs, Speed Camera Violations https://data.cityofchicago.org/view/gncf-3xbx) and Affordable Housing (https://data.cityofchicago.org/view/dkgm-i9fi) are good starting points.

**Comment by afrasier** [comment]
http://uscensusbureau.github.io/citysdk/apps/chicagoCAD/

Will add a few extra features, and some extra comments in the code
