### ISSUE TITLE
Increase the number of aliased variables

### ISSUE THREAD

**Issue by afrasier** [uscensusbureau/citysdk#98]
Increase the number of aliased variables

Externalize the alias file (though this means tracking MORE files for end users - perhaps we can store it on a CDN or in it's own repo?)

Add "statistical"  variables (i.e. margin of error) aliases

**Comment by lgangas** [comment]
Glossary search/items functions will cover what data do they get back from pull requests

**Comment by philipashlock** [comment]
You might also consider the approach of a separate API for querying variables since it wouldn't be practical to include an 11mb JSON file as part of the SDK. The Census "Find it Connect it" initiative is taking the approach of a metadata registry system like this http://ds3.cnri.net/registrar/

**Comment by lgangas** [comment]
Look at the HUD ACS variables

**Comment by afrasier** [comment]
Resolved f1cabdf45be7797e9b3266c39a6b0db60db7549e
